/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const CreateContestMetadataResponseContestManagersItemContestsItemActionsItemAction: core.serialization.Schema<
    serializers.CreateContestMetadataResponseContestManagersItemContestsItemActionsItemAction.Raw,
    CommonApi.CreateContestMetadataResponseContestManagersItemContestsItemActionsItemAction
> = core.serialization.enum_(["added", "upvoted"]);

export declare namespace CreateContestMetadataResponseContestManagersItemContestsItemActionsItemAction {
    type Raw = "added" | "upvoted";
}
