/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const CreateTopicResponseTopicWeightedVoting: core.serialization.Schema<
    serializers.CreateTopicResponseTopicWeightedVoting.Raw,
    CommonApi.CreateTopicResponseTopicWeightedVoting
> = core.serialization.enum_(["stake", "erc20"]);

export declare namespace CreateTopicResponseTopicWeightedVoting {
    type Raw = "stake" | "erc20";
}
