/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { CreateTopicResponseTopic } from "./CreateTopicResponseTopic";

export const CreateTopicResponse: core.serialization.ObjectSchema<
    serializers.CreateTopicResponse.Raw,
    CommonApi.CreateTopicResponse
> = core.serialization.object({
    topic: CreateTopicResponseTopic,
    userId: core.serialization.property("user_id", core.serialization.number()),
});

export declare namespace CreateTopicResponse {
    interface Raw {
        topic: CreateTopicResponseTopic.Raw;
        user_id: number;
    }
}
