/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const CreateContestMetadataResponseContestManagersItemTopicsItemWeightedVoting: core.serialization.Schema<
    serializers.CreateContestMetadataResponseContestManagersItemTopicsItemWeightedVoting.Raw,
    CommonApi.CreateContestMetadataResponseContestManagersItemTopicsItemWeightedVoting
> = core.serialization.enum_(["stake", "erc20"]);

export declare namespace CreateContestMetadataResponseContestManagersItemTopicsItemWeightedVoting {
    type Raw = "stake" | "erc20";
}
