/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const CreateCommunityResponseCommunityGroupsItemRequirementsItemThresholdDataSourceThreeSourceType: core.serialization.Schema<
    serializers.CreateCommunityResponseCommunityGroupsItemRequirementsItemThresholdDataSourceThreeSourceType.Raw,
    CommonApi.CreateCommunityResponseCommunityGroupsItemRequirementsItemThresholdDataSourceThreeSourceType
> = core.serialization.enum_(["cw721", "cw20"]);

export declare namespace CreateCommunityResponseCommunityGroupsItemRequirementsItemThresholdDataSourceThreeSourceType {
    type Raw = "cw721" | "cw20";
}
