/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const CreateGroupResponseTopicsItemWeightedVoting: core.serialization.Schema<
    serializers.CreateGroupResponseTopicsItemWeightedVoting.Raw,
    CommonApi.CreateGroupResponseTopicsItemWeightedVoting
> = core.serialization.enum_(["stake", "erc20"]);

export declare namespace CreateGroupResponseTopicsItemWeightedVoting {
    type Raw = "stake" | "erc20";
}
