/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const CreateCommunityResponseCommunitySocialLinksItem: core.serialization.Schema<
    serializers.CreateCommunityResponseCommunitySocialLinksItem.Raw,
    CommonApi.CreateCommunityResponseCommunitySocialLinksItem
> = core.serialization.undiscriminatedUnion([core.serialization.unknown(), core.serialization.string().optional()]);

export declare namespace CreateCommunityResponseCommunitySocialLinksItem {
    type Raw = unknown | (string | null | undefined);
}
