/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { CreateCommunityResponseCommunityGroupsItemRequirementsItemThresholdData } from "./CreateCommunityResponseCommunityGroupsItemRequirementsItemThresholdData";

export const CreateCommunityResponseCommunityGroupsItemRequirementsItemThreshold: core.serialization.ObjectSchema<
    serializers.CreateCommunityResponseCommunityGroupsItemRequirementsItemThreshold.Raw,
    CommonApi.CreateCommunityResponseCommunityGroupsItemRequirementsItemThreshold
> = core.serialization.object({
    data: CreateCommunityResponseCommunityGroupsItemRequirementsItemThresholdData,
});

export declare namespace CreateCommunityResponseCommunityGroupsItemRequirementsItemThreshold {
    interface Raw {
        data: CreateCommunityResponseCommunityGroupsItemRequirementsItemThresholdData.Raw;
    }
}
