/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { CreateGroupRequestRequirementsItemThresholdDataSourceThreeSourceType } from "./CreateGroupRequestRequirementsItemThresholdDataSourceThreeSourceType";

export const CreateGroupRequestRequirementsItemThresholdDataSourceThree: core.serialization.ObjectSchema<
    serializers.CreateGroupRequestRequirementsItemThresholdDataSourceThree.Raw,
    CommonApi.CreateGroupRequestRequirementsItemThresholdDataSourceThree
> = core.serialization.object({
    sourceType: core.serialization.property(
        "source_type",
        CreateGroupRequestRequirementsItemThresholdDataSourceThreeSourceType
    ),
    cosmosChainId: core.serialization.property("cosmos_chain_id", core.serialization.string()),
    contractAddress: core.serialization.property("contract_address", core.serialization.string()),
});

export declare namespace CreateGroupRequestRequirementsItemThresholdDataSourceThree {
    interface Raw {
        source_type: CreateGroupRequestRequirementsItemThresholdDataSourceThreeSourceType.Raw;
        cosmos_chain_id: string;
        contract_address: string;
    }
}
