/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const CreateCommunityResponseCommunityGroupsItemRequirementsItemAllowData: core.serialization.ObjectSchema<
    serializers.CreateCommunityResponseCommunityGroupsItemRequirementsItemAllowData.Raw,
    CommonApi.CreateCommunityResponseCommunityGroupsItemRequirementsItemAllowData
> = core.serialization.object({
    allow: core.serialization.list(core.serialization.string()),
});

export declare namespace CreateCommunityResponseCommunityGroupsItemRequirementsItemAllowData {
    interface Raw {
        allow: string[];
    }
}
