/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const CreateCommunityResponseCommunityTopicsItemWeightedVoting: core.serialization.Schema<
    serializers.CreateCommunityResponseCommunityTopicsItemWeightedVoting.Raw,
    CommonApi.CreateCommunityResponseCommunityTopicsItemWeightedVoting
> = core.serialization.enum_(["stake", "erc20"]);

export declare namespace CreateCommunityResponseCommunityTopicsItemWeightedVoting {
    type Raw = "stake" | "erc20";
}
