/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const CreateCommunityResponseCommunityCommunityStakesItemStakeTransactionsItemStakeDirection: core.serialization.Schema<
    serializers.CreateCommunityResponseCommunityCommunityStakesItemStakeTransactionsItemStakeDirection.Raw,
    CommonApi.CreateCommunityResponseCommunityCommunityStakesItemStakeTransactionsItemStakeDirection
> = core.serialization.enum_(["buy", "sell"]);

export declare namespace CreateCommunityResponseCommunityCommunityStakesItemStakeTransactionsItemStakeDirection {
    type Raw = "buy" | "sell";
}
