/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { CreateGroupRequestRequirementsItemThreshold } from "./CreateGroupRequestRequirementsItemThreshold";
import { CreateGroupRequestRequirementsItemAllow } from "./CreateGroupRequestRequirementsItemAllow";

export const CreateGroupRequestRequirementsItem: core.serialization.Schema<
    serializers.CreateGroupRequestRequirementsItem.Raw,
    CommonApi.CreateGroupRequestRequirementsItem
> = core.serialization
    .union("rule", {
        threshold: CreateGroupRequestRequirementsItemThreshold,
        allow: CreateGroupRequestRequirementsItemAllow,
    })
    .transform<CommonApi.CreateGroupRequestRequirementsItem>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace CreateGroupRequestRequirementsItem {
    type Raw = CreateGroupRequestRequirementsItem.Threshold | CreateGroupRequestRequirementsItem.Allow;

    interface Threshold extends CreateGroupRequestRequirementsItemThreshold.Raw {
        rule: "threshold";
    }

    interface Allow extends CreateGroupRequestRequirementsItemAllow.Raw {
        rule: "allow";
    }
}
