/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { CreateCommunityResponseCommunityGroupsItemMetadata } from "./CreateCommunityResponseCommunityGroupsItemMetadata";
import { CreateCommunityResponseCommunityGroupsItemRequirementsItem } from "./CreateCommunityResponseCommunityGroupsItemRequirementsItem";

export const CreateCommunityResponseCommunityGroupsItem: core.serialization.ObjectSchema<
    serializers.CreateCommunityResponseCommunityGroupsItem.Raw,
    CommonApi.CreateCommunityResponseCommunityGroupsItem
> = core.serialization.object({
    id: core.serialization.number().optional(),
    communityId: core.serialization.property("community_id", core.serialization.string()),
    metadata: CreateCommunityResponseCommunityGroupsItemMetadata,
    requirements: core.serialization.list(CreateCommunityResponseCommunityGroupsItemRequirementsItem),
    isSystemManaged: core.serialization.property("is_system_managed", core.serialization.boolean().optional()),
    createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date().optional()),
});

export declare namespace CreateCommunityResponseCommunityGroupsItem {
    interface Raw {
        id?: number | null;
        community_id: string;
        metadata: CreateCommunityResponseCommunityGroupsItemMetadata.Raw;
        requirements: CreateCommunityResponseCommunityGroupsItemRequirementsItem.Raw[];
        is_system_managed?: boolean | null;
        created_at?: string | null;
        updated_at?: string | null;
    }
}
