/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { CreateGroupRequestRequirementsItemThresholdDataSource } from "./CreateGroupRequestRequirementsItemThresholdDataSource";

export const CreateGroupRequestRequirementsItemThresholdData: core.serialization.ObjectSchema<
    serializers.CreateGroupRequestRequirementsItemThresholdData.Raw,
    CommonApi.CreateGroupRequestRequirementsItemThresholdData
> = core.serialization.object({
    threshold: core.serialization.string(),
    source: CreateGroupRequestRequirementsItemThresholdDataSource,
});

export declare namespace CreateGroupRequestRequirementsItemThresholdData {
    interface Raw {
        threshold: string;
        source: CreateGroupRequestRequirementsItemThresholdDataSource.Raw;
    }
}
