/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const CreateCommunityResponseCommunityChainNodeBalanceType: core.serialization.Schema<
    serializers.CreateCommunityResponseCommunityChainNodeBalanceType.Raw,
    CommonApi.CreateCommunityResponseCommunityChainNodeBalanceType
> = core.serialization.enum_(["terra", "ethereum", "solana", "cosmos", "near", "substrate"]);

export declare namespace CreateCommunityResponseCommunityChainNodeBalanceType {
    type Raw = "terra" | "ethereum" | "solana" | "cosmos" | "near" | "substrate";
}
