/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetCommunityResponseAddressesAddressesItemRole: core.serialization.Schema<
    serializers.GetCommunityResponseAddressesAddressesItemRole.Raw,
    CommonApi.GetCommunityResponseAddressesAddressesItemRole
> = core.serialization.enum_(["admin", "moderator", "member"]);

export declare namespace GetCommunityResponseAddressesAddressesItemRole {
    type Raw = "admin" | "moderator" | "member";
}
