/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetCommunityResponseAddressesGroupsItemRequirementsItemThresholdDataSourceThreeSourceType } from "./GetCommunityResponseAddressesGroupsItemRequirementsItemThresholdDataSourceThreeSourceType";

export const GetCommunityResponseAddressesGroupsItemRequirementsItemThresholdDataSourceThree: core.serialization.ObjectSchema<
    serializers.GetCommunityResponseAddressesGroupsItemRequirementsItemThresholdDataSourceThree.Raw,
    CommonApi.GetCommunityResponseAddressesGroupsItemRequirementsItemThresholdDataSourceThree
> = core.serialization.object({
    sourceType: core.serialization.property(
        "source_type",
        GetCommunityResponseAddressesGroupsItemRequirementsItemThresholdDataSourceThreeSourceType
    ),
    cosmosChainId: core.serialization.property("cosmos_chain_id", core.serialization.string()),
    contractAddress: core.serialization.property("contract_address", core.serialization.string()),
});

export declare namespace GetCommunityResponseAddressesGroupsItemRequirementsItemThresholdDataSourceThree {
    interface Raw {
        source_type: GetCommunityResponseAddressesGroupsItemRequirementsItemThresholdDataSourceThreeSourceType.Raw;
        cosmos_chain_id: string;
        contract_address: string;
    }
}
