/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetCommunityResponseAddressesContestManagersItemContestsItemActionsItemAction: core.serialization.Schema<
    serializers.GetCommunityResponseAddressesContestManagersItemContestsItemActionsItemAction.Raw,
    CommonApi.GetCommunityResponseAddressesContestManagersItemContestsItemActionsItemAction
> = core.serialization.enum_(["added", "upvoted"]);

export declare namespace GetCommunityResponseAddressesContestManagersItemContestsItemActionsItemAction {
    type Raw = "added" | "upvoted";
}
