/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetCommunityResponseAddressesTermsZero: core.serialization.Schema<
    serializers.GetCommunityResponseAddressesTermsZero.Raw,
    CommonApi.GetCommunityResponseAddressesTermsZero
> = core.serialization.undiscriminatedUnion([core.serialization.string(), core.serialization.stringLiteral("")]);

export declare namespace GetCommunityResponseAddressesTermsZero {
    type Raw = string | "";
}
