/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetCommunitiesResponseResultsItemType: core.serialization.Schema<
    serializers.GetCommunitiesResponseResultsItemType.Raw,
    CommonApi.GetCommunitiesResponseResultsItemType
> = core.serialization.enum_(["chain", "dao", "token", "offchain"]);

export declare namespace GetCommunitiesResponseResultsItemType {
    type Raw = "chain" | "dao" | "token" | "offchain";
}
