/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetCommunityResponseAddressesAdminsAndModsItemRole } from "./GetCommunityResponseAddressesAdminsAndModsItemRole";

export const GetCommunityResponseAddressesAdminsAndModsItem: core.serialization.ObjectSchema<
    serializers.GetCommunityResponseAddressesAdminsAndModsItem.Raw,
    CommonApi.GetCommunityResponseAddressesAdminsAndModsItem
> = core.serialization.object({
    address: core.serialization.string(),
    role: GetCommunityResponseAddressesAdminsAndModsItemRole,
});

export declare namespace GetCommunityResponseAddressesAdminsAndModsItem {
    interface Raw {
        address: string;
        role: GetCommunityResponseAddressesAdminsAndModsItemRole.Raw;
    }
}
