/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetCommunitiesResponseResultsItemSocialLinksItem: core.serialization.Schema<
    serializers.GetCommunitiesResponseResultsItemSocialLinksItem.Raw,
    CommonApi.GetCommunitiesResponseResultsItemSocialLinksItem
> = core.serialization.undiscriminatedUnion([core.serialization.unknown(), core.serialization.string().optional()]);

export declare namespace GetCommunitiesResponseResultsItemSocialLinksItem {
    type Raw = unknown | (string | null | undefined);
}
