/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetCommunityResponseAddressesSocialLinksItem: core.serialization.Schema<
    serializers.GetCommunityResponseAddressesSocialLinksItem.Raw,
    CommonApi.GetCommunityResponseAddressesSocialLinksItem
> = core.serialization.undiscriminatedUnion([core.serialization.unknown(), core.serialization.string().optional()]);

export declare namespace GetCommunityResponseAddressesSocialLinksItem {
    type Raw = unknown | (string | null | undefined);
}
