/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetCommunitiesResponseResultsItemContestManagersItemTopicsItemWeightedVoting: core.serialization.Schema<
    serializers.GetCommunitiesResponseResultsItemContestManagersItemTopicsItemWeightedVoting.Raw,
    CommonApi.GetCommunitiesResponseResultsItemContestManagersItemTopicsItemWeightedVoting
> = core.serialization.enum_(["stake", "erc20"]);

export declare namespace GetCommunitiesResponseResultsItemContestManagersItemTopicsItemWeightedVoting {
    type Raw = "stake" | "erc20";
}
