/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetMembersResponseResultsItemAddressesItemRole: core.serialization.Schema<
    serializers.GetMembersResponseResultsItemAddressesItemRole.Raw,
    CommonApi.GetMembersResponseResultsItemAddressesItemRole
> = core.serialization.enum_(["admin", "moderator", "member"]);

export declare namespace GetMembersResponseResultsItemAddressesItemRole {
    type Raw = "admin" | "moderator" | "member";
}
