/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const UpdateGroupRequestRequirementsItemThresholdDataSourceTokenIdSourceType: core.serialization.Schema<
    serializers.UpdateGroupRequestRequirementsItemThresholdDataSourceTokenIdSourceType.Raw,
    CommonApi.UpdateGroupRequestRequirementsItemThresholdDataSourceTokenIdSourceType
> = core.serialization.enum_(["erc20", "erc721", "erc1155", "spl"]);

export declare namespace UpdateGroupRequestRequirementsItemThresholdDataSourceTokenIdSourceType {
    type Raw = "erc20" | "erc721" | "erc1155" | "spl";
}
