/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { UpdateCommunityResponseGroupsItemRequirementsItemThresholdDataSource } from "./UpdateCommunityResponseGroupsItemRequirementsItemThresholdDataSource";

export const UpdateCommunityResponseGroupsItemRequirementsItemThresholdData: core.serialization.ObjectSchema<
    serializers.UpdateCommunityResponseGroupsItemRequirementsItemThresholdData.Raw,
    CommonApi.UpdateCommunityResponseGroupsItemRequirementsItemThresholdData
> = core.serialization.object({
    threshold: core.serialization.string(),
    source: UpdateCommunityResponseGroupsItemRequirementsItemThresholdDataSource,
});

export declare namespace UpdateCommunityResponseGroupsItemRequirementsItemThresholdData {
    interface Raw {
        threshold: string;
        source: UpdateCommunityResponseGroupsItemRequirementsItemThresholdDataSource.Raw;
    }
}
