/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const UpdateCommunityResponseAddressesItemUserEmailNotificationInterval: core.serialization.Schema<
    serializers.UpdateCommunityResponseAddressesItemUserEmailNotificationInterval.Raw,
    CommonApi.UpdateCommunityResponseAddressesItemUserEmailNotificationInterval
> = core.serialization.enum_(["weekly", "never"]);

export declare namespace UpdateCommunityResponseAddressesItemUserEmailNotificationInterval {
    type Raw = "weekly" | "never";
}
