/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { UpdateCommunityRequestCommunityStakesItemStakeTransactionsItemStakeDirection } from "./UpdateCommunityRequestCommunityStakesItemStakeTransactionsItemStakeDirection";

export const UpdateCommunityRequestCommunityStakesItemStakeTransactionsItem: core.serialization.ObjectSchema<
    serializers.UpdateCommunityRequestCommunityStakesItemStakeTransactionsItem.Raw,
    CommonApi.UpdateCommunityRequestCommunityStakesItemStakeTransactionsItem
> = core.serialization.object({
    transactionHash: core.serialization.property("transaction_hash", core.serialization.string()),
    communityId: core.serialization.property("community_id", core.serialization.string()),
    stakeId: core.serialization.property("stake_id", core.serialization.number().optional()),
    address: core.serialization.string(),
    stakeAmount: core.serialization.property("stake_amount", core.serialization.number()),
    stakePrice: core.serialization.property("stake_price", core.serialization.string().optional()),
    stakeDirection: core.serialization.property(
        "stake_direction",
        UpdateCommunityRequestCommunityStakesItemStakeTransactionsItemStakeDirection
    ),
    timestamp: core.serialization.number(),
});

export declare namespace UpdateCommunityRequestCommunityStakesItemStakeTransactionsItem {
    interface Raw {
        transaction_hash: string;
        community_id: string;
        stake_id?: number | null;
        address: string;
        stake_amount: number;
        stake_price?: string | null;
        stake_direction: UpdateCommunityRequestCommunityStakesItemStakeTransactionsItemStakeDirection.Raw;
        timestamp: number;
    }
}
