/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const UpdateCommunityRequestAddressesItemRole: core.serialization.Schema<
    serializers.UpdateCommunityRequestAddressesItemRole.Raw,
    CommonApi.UpdateCommunityRequestAddressesItemRole
> = core.serialization.enum_(["admin", "moderator", "member"]);

export declare namespace UpdateCommunityRequestAddressesItemRole {
    type Raw = "admin" | "moderator" | "member";
}
