/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { UpdateCommunityResponseTermsZero } from "./UpdateCommunityResponseTermsZero";

export const UpdateCommunityResponseTerms: core.serialization.Schema<
    serializers.UpdateCommunityResponseTerms.Raw,
    CommonApi.UpdateCommunityResponseTerms
> = core.serialization.undiscriminatedUnion([UpdateCommunityResponseTermsZero, core.serialization.string()]);

export declare namespace UpdateCommunityResponseTerms {
    type Raw = UpdateCommunityResponseTermsZero.Raw | string;
}
