/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { UpdateCommunityResponseCommunityTagsItemTag } from "./UpdateCommunityResponseCommunityTagsItemTag";

export const UpdateCommunityResponseCommunityTagsItem: core.serialization.ObjectSchema<
    serializers.UpdateCommunityResponseCommunityTagsItem.Raw,
    CommonApi.UpdateCommunityResponseCommunityTagsItem
> = core.serialization.object({
    communityId: core.serialization.property("community_id", core.serialization.string()),
    tagId: core.serialization.property("tag_id", core.serialization.number()),
    tag: core.serialization.property("Tag", UpdateCommunityResponseCommunityTagsItemTag.optional()),
});

export declare namespace UpdateCommunityResponseCommunityTagsItem {
    interface Raw {
        community_id: string;
        tag_id: number;
        Tag?: UpdateCommunityResponseCommunityTagsItemTag.Raw | null;
    }
}
