/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const UpdateGroupRequestRequirementsItemAllowData: core.serialization.ObjectSchema<
    serializers.UpdateGroupRequestRequirementsItemAllowData.Raw,
    CommonApi.UpdateGroupRequestRequirementsItemAllowData
> = core.serialization.object({
    allow: core.serialization.list(core.serialization.string()),
});

export declare namespace UpdateGroupRequestRequirementsItemAllowData {
    interface Raw {
        allow: string[];
    }
}
