/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const UpdateCommunityRequestContestManagersItemTopicsItemWeightedVoting: core.serialization.Schema<
    serializers.UpdateCommunityRequestContestManagersItemTopicsItemWeightedVoting.Raw,
    CommonApi.UpdateCommunityRequestContestManagersItemTopicsItemWeightedVoting
> = core.serialization.enum_(["stake", "erc20"]);

export declare namespace UpdateCommunityRequestContestManagersItemTopicsItemWeightedVoting {
    type Raw = "stake" | "erc20";
}
