/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { UpdateCommunityRequestAddressesItemUserProfileTagsItemTag } from "./UpdateCommunityRequestAddressesItemUserProfileTagsItemTag";

export const UpdateCommunityRequestAddressesItemUserProfileTagsItem: core.serialization.ObjectSchema<
    serializers.UpdateCommunityRequestAddressesItemUserProfileTagsItem.Raw,
    CommonApi.UpdateCommunityRequestAddressesItemUserProfileTagsItem
> = core.serialization.object({
    userId: core.serialization.property("user_id", core.serialization.number()),
    tagId: core.serialization.property("tag_id", core.serialization.number()),
    createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date().optional()),
    tag: core.serialization.property("Tag", UpdateCommunityRequestAddressesItemUserProfileTagsItemTag.optional()),
});

export declare namespace UpdateCommunityRequestAddressesItemUserProfileTagsItem {
    interface Raw {
        user_id: number;
        tag_id: number;
        created_at?: string | null;
        updated_at?: string | null;
        Tag?: UpdateCommunityRequestAddressesItemUserProfileTagsItemTag.Raw | null;
    }
}
