/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { UpdateContestMetadataResponseContestManagersItem } from "./UpdateContestMetadataResponseContestManagersItem";

export const UpdateContestMetadataResponse: core.serialization.ObjectSchema<
    serializers.UpdateContestMetadataResponse.Raw,
    CommonApi.UpdateContestMetadataResponse
> = core.serialization.object({
    contestManagers: core.serialization.property(
        "contest_managers",
        core.serialization.list(UpdateContestMetadataResponseContestManagersItem)
    ),
});

export declare namespace UpdateContestMetadataResponse {
    interface Raw {
        contest_managers: UpdateContestMetadataResponseContestManagersItem.Raw[];
    }
}
