/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { UpdateGroupRequestRequirementsItemThresholdDataSourceTokenId } from "./UpdateGroupRequestRequirementsItemThresholdDataSourceTokenId";
import { UpdateGroupRequestRequirementsItemThresholdDataSourceOne } from "./UpdateGroupRequestRequirementsItemThresholdDataSourceOne";
import { UpdateGroupRequestRequirementsItemThresholdDataSourceTokenSymbol } from "./UpdateGroupRequestRequirementsItemThresholdDataSourceTokenSymbol";
import { UpdateGroupRequestRequirementsItemThresholdDataSourceThree } from "./UpdateGroupRequestRequirementsItemThresholdDataSourceThree";

export const UpdateGroupRequestRequirementsItemThresholdDataSource: core.serialization.Schema<
    serializers.UpdateGroupRequestRequirementsItemThresholdDataSource.Raw,
    CommonApi.UpdateGroupRequestRequirementsItemThresholdDataSource
> = core.serialization.undiscriminatedUnion([
    UpdateGroupRequestRequirementsItemThresholdDataSourceTokenId,
    UpdateGroupRequestRequirementsItemThresholdDataSourceOne,
    UpdateGroupRequestRequirementsItemThresholdDataSourceTokenSymbol,
    UpdateGroupRequestRequirementsItemThresholdDataSourceThree,
]);

export declare namespace UpdateGroupRequestRequirementsItemThresholdDataSource {
    type Raw =
        | UpdateGroupRequestRequirementsItemThresholdDataSourceTokenId.Raw
        | UpdateGroupRequestRequirementsItemThresholdDataSourceOne.Raw
        | UpdateGroupRequestRequirementsItemThresholdDataSourceTokenSymbol.Raw
        | UpdateGroupRequestRequirementsItemThresholdDataSourceThree.Raw;
}
