/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSourceThreeSourceType } from "./UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSourceThreeSourceType";

export const UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSourceThree: core.serialization.ObjectSchema<
    serializers.UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSourceThree.Raw,
    CommonApi.UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSourceThree
> = core.serialization.object({
    sourceType: core.serialization.property(
        "source_type",
        UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSourceThreeSourceType
    ),
    cosmosChainId: core.serialization.property("cosmos_chain_id", core.serialization.string()),
    contractAddress: core.serialization.property("contract_address", core.serialization.string()),
});

export declare namespace UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSourceThree {
    interface Raw {
        source_type: UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSourceThreeSourceType.Raw;
        cosmos_chain_id: string;
        contract_address: string;
    }
}
