/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const UpdateCommunityResponseTermsZero: core.serialization.Schema<
    serializers.UpdateCommunityResponseTermsZero.Raw,
    CommonApi.UpdateCommunityResponseTermsZero
> = core.serialization.undiscriminatedUnion([core.serialization.string(), core.serialization.stringLiteral("")]);

export declare namespace UpdateCommunityResponseTermsZero {
    type Raw = string | "";
}
