/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { UpdateCommunityRequestGroupsItemMetadata } from "./UpdateCommunityRequestGroupsItemMetadata";
import { UpdateCommunityRequestGroupsItemRequirementsItem } from "./UpdateCommunityRequestGroupsItemRequirementsItem";

export const UpdateCommunityRequestGroupsItem: core.serialization.ObjectSchema<
    serializers.UpdateCommunityRequestGroupsItem.Raw,
    CommonApi.UpdateCommunityRequestGroupsItem
> = core.serialization.object({
    id: core.serialization.number().optional(),
    communityId: core.serialization.property("community_id", core.serialization.string()),
    metadata: UpdateCommunityRequestGroupsItemMetadata,
    requirements: core.serialization.list(UpdateCommunityRequestGroupsItemRequirementsItem),
    isSystemManaged: core.serialization.property("is_system_managed", core.serialization.boolean().optional()),
    createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date().optional()),
});

export declare namespace UpdateCommunityRequestGroupsItem {
    interface Raw {
        id?: number | null;
        community_id: string;
        metadata: UpdateCommunityRequestGroupsItemMetadata.Raw;
        requirements: UpdateCommunityRequestGroupsItemRequirementsItem.Raw[];
        is_system_managed?: boolean | null;
        created_at?: string | null;
        updated_at?: string | null;
    }
}
