/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { UpdateCommunityRequestTermsZero } from "./UpdateCommunityRequestTermsZero";

export const UpdateCommunityRequestTerms: core.serialization.Schema<
    serializers.UpdateCommunityRequestTerms.Raw,
    CommonApi.UpdateCommunityRequestTerms
> = core.serialization.undiscriminatedUnion([UpdateCommunityRequestTermsZero, core.serialization.string()]);

export declare namespace UpdateCommunityRequestTerms {
    type Raw = UpdateCommunityRequestTermsZero.Raw | string;
}
