/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { UpdateCommunityRequestGroupsItemRequirementsItemThreshold } from "./UpdateCommunityRequestGroupsItemRequirementsItemThreshold";
import { UpdateCommunityRequestGroupsItemRequirementsItemAllow } from "./UpdateCommunityRequestGroupsItemRequirementsItemAllow";

export const UpdateCommunityRequestGroupsItemRequirementsItem: core.serialization.Schema<
    serializers.UpdateCommunityRequestGroupsItemRequirementsItem.Raw,
    CommonApi.UpdateCommunityRequestGroupsItemRequirementsItem
> = core.serialization
    .union("rule", {
        threshold: UpdateCommunityRequestGroupsItemRequirementsItemThreshold,
        allow: UpdateCommunityRequestGroupsItemRequirementsItemAllow,
    })
    .transform<CommonApi.UpdateCommunityRequestGroupsItemRequirementsItem>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace UpdateCommunityRequestGroupsItemRequirementsItem {
    type Raw =
        | UpdateCommunityRequestGroupsItemRequirementsItem.Threshold
        | UpdateCommunityRequestGroupsItemRequirementsItem.Allow;

    interface Threshold extends UpdateCommunityRequestGroupsItemRequirementsItemThreshold.Raw {
        rule: "threshold";
    }

    interface Allow extends UpdateCommunityRequestGroupsItemRequirementsItemAllow.Raw {
        rule: "allow";
    }
}
