/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const UpdateCommunityRequestSnapshot: core.serialization.Schema<
    serializers.UpdateCommunityRequestSnapshot.Raw,
    CommonApi.UpdateCommunityRequestSnapshot
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.list(core.serialization.string()),
]);

export declare namespace UpdateCommunityRequestSnapshot {
    type Raw = string | string[];
}
