/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const UpdateCommunityRequestHasHomepage: core.serialization.Schema<
    serializers.UpdateCommunityRequestHasHomepage.Raw,
    CommonApi.UpdateCommunityRequestHasHomepage
> = core.serialization.enum_(["true", "false"]);

export declare namespace UpdateCommunityRequestHasHomepage {
    type Raw = "true" | "false";
}
