/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { UpdateGroupRequestRequirementsItemThresholdDataSourceTokenIdSourceType } from "./UpdateGroupRequestRequirementsItemThresholdDataSourceTokenIdSourceType";

export const UpdateGroupRequestRequirementsItemThresholdDataSourceTokenId: core.serialization.ObjectSchema<
    serializers.UpdateGroupRequestRequirementsItemThresholdDataSourceTokenId.Raw,
    CommonApi.UpdateGroupRequestRequirementsItemThresholdDataSourceTokenId
> = core.serialization.object({
    sourceType: core.serialization.property(
        "source_type",
        UpdateGroupRequestRequirementsItemThresholdDataSourceTokenIdSourceType
    ),
    evmChainId: core.serialization.property("evm_chain_id", core.serialization.number()),
    contractAddress: core.serialization.property("contract_address", core.serialization.string()),
    tokenId: core.serialization.property("token_id", core.serialization.string().optional()),
});

export declare namespace UpdateGroupRequestRequirementsItemThresholdDataSourceTokenId {
    interface Raw {
        source_type: UpdateGroupRequestRequirementsItemThresholdDataSourceTokenIdSourceType.Raw;
        evm_chain_id: number;
        contract_address: string;
        token_id?: string | null;
    }
}
