/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const UpdateGroupResponseRequirementsItemThresholdDataSourceThreeSourceType: core.serialization.Schema<
    serializers.UpdateGroupResponseRequirementsItemThresholdDataSourceThreeSourceType.Raw,
    CommonApi.UpdateGroupResponseRequirementsItemThresholdDataSourceThreeSourceType
> = core.serialization.enum_(["cw721", "cw20"]);

export declare namespace UpdateGroupResponseRequirementsItemThresholdDataSourceThreeSourceType {
    type Raw = "cw721" | "cw20";
}
