/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { UpdateGroupResponseRequirementsItemThresholdData } from "./UpdateGroupResponseRequirementsItemThresholdData";

export const UpdateGroupResponseRequirementsItemThreshold: core.serialization.ObjectSchema<
    serializers.UpdateGroupResponseRequirementsItemThreshold.Raw,
    CommonApi.UpdateGroupResponseRequirementsItemThreshold
> = core.serialization.object({
    data: UpdateGroupResponseRequirementsItemThresholdData,
});

export declare namespace UpdateGroupResponseRequirementsItemThreshold {
    interface Raw {
        data: UpdateGroupResponseRequirementsItemThresholdData.Raw;
    }
}
