/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const UpdateCommunityResponseContestManagersItemContestsItemActionsItemAction: core.serialization.Schema<
    serializers.UpdateCommunityResponseContestManagersItemContestsItemActionsItemAction.Raw,
    CommonApi.UpdateCommunityResponseContestManagersItemContestsItemActionsItemAction
> = core.serialization.enum_(["added", "upvoted"]);

export declare namespace UpdateCommunityResponseContestManagersItemContestsItemActionsItemAction {
    type Raw = "added" | "upvoted";
}
