/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSourceThreeSourceType: core.serialization.Schema<
    serializers.UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSourceThreeSourceType.Raw,
    CommonApi.UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSourceThreeSourceType
> = core.serialization.enum_(["cw721", "cw20"]);

export declare namespace UpdateCommunityRequestGroupsItemRequirementsItemThresholdDataSourceThreeSourceType {
    type Raw = "cw721" | "cw20";
}
