/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { UpdateCommunityRequestGroupsItemRequirementsItemThresholdData } from "./UpdateCommunityRequestGroupsItemRequirementsItemThresholdData";

export const UpdateCommunityRequestGroupsItemRequirementsItemThreshold: core.serialization.ObjectSchema<
    serializers.UpdateCommunityRequestGroupsItemRequirementsItemThreshold.Raw,
    CommonApi.UpdateCommunityRequestGroupsItemRequirementsItemThreshold
> = core.serialization.object({
    data: UpdateCommunityRequestGroupsItemRequirementsItemThresholdData,
});

export declare namespace UpdateCommunityRequestGroupsItemRequirementsItemThreshold {
    interface Raw {
        data: UpdateCommunityRequestGroupsItemRequirementsItemThresholdData.Raw;
    }
}
