/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         eth_chain_id: 1.1,
 *         transaction_hash: "transaction_hash"
 *     }
 */
export interface CreateTradeRequest {
    eth_chain_id: number;
    transaction_hash: string;
}
