/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         community_id: "community_id",
 *         topic_id: 1
 *     }
 */
export interface DeleteTopicRequest {
    community_id: string;
    topic_id: number;
}
