/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../../index";

/**
 * @example
 *     {
 *         community_id: "community_id"
 *     }
 */
export interface GetMembersRequest {
    limit?: string;
    /**
     * required for tRPC useInfiniteQuery hook, equivalent to page number
     */
    cursor?: string;
    order_by?: CommonApi.GetMembersRequestOrderBy;
    order_direction?: CommonApi.GetMembersRequestOrderDirection;
    search?: string;
    community_id: string;
    include_roles?: boolean;
    memberships?: CommonApi.GetMembersRequestMemberships;
    include_group_ids?: boolean;
    include_stake_balances?: boolean;
    allowedAddresses?: string;
    searchByNameAndAddress?: string;
}
