/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         communityId: "community_id"
 *     }
 */
export interface GetTopicsRequest {
    communityId: string;
    withContestManagers?: boolean;
    withArchivedTopics?: boolean;
}
