/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         communityId: "community_id",
 *         contestAddress: "contest_address"
 *     }
 */
export interface UpdateContestMetadataRequest {
    communityId: string;
    /** On-Chain contest manager address */
    contestAddress: string;
    name?: string;
    imageUrl?: string;
    topicId?: number;
}
