/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         community_id: "community_id",
 *         contest_address: "contest_address"
 *     }
 */
export interface UpdateContestMetadataRequest {
    community_id: string;
    /** On-Chain contest manager address */
    contest_address: string;
    name?: string;
    description?: string;
    image_url?: string;
    topic_id?: number;
    namespace_judge_token_id?: number;
}
