/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../../index";

/**
 * @example
 *     {
 *         community_id: "community_id",
 *         group_id: 1
 *     }
 */
export interface UpdateGroupRequest {
    community_id: string;
    group_id: number;
    metadata?: CommonApi.UpdateGroupRequestMetadata;
    requirements?: CommonApi.UpdateGroupRequestRequirementsItem[];
    topics?: CommonApi.UpdateGroupRequestTopicsItem[];
}
