/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../../index";

/**
 * @example
 *     {
 *         community_id: "community_id"
 *     }
 */
export interface UpdateCommunityRequest {
    name?: string;
    chain_node_id?: number;
    default_symbol?: string;
    base?: CommonApi.UpdateCommunityRequestBase;
    icon_url?: string;
    active?: boolean;
    type?: CommonApi.UpdateCommunityRequestType;
    description?: string;
    social_links?: CommonApi.UpdateCommunityRequestSocialLinksItem[];
    ss58_prefix?: number;
    stages_enabled?: boolean;
    custom_stages?: string[];
    block_explorer_ids?: string;
    collapsed_on_homepage?: boolean;
    default_summary_view?: boolean;
    default_page?: CommonApi.UpdateCommunityRequestDefaultPage;
    has_homepage?: CommonApi.UpdateCommunityRequestHasHomepage;
    terms?: CommonApi.UpdateCommunityRequestTerms;
    admin_only_polling?: boolean;
    bech32_prefix?: string;
    hide_projects?: boolean;
    token_name?: string;
    ce_verbose?: boolean;
    discord_config_id?: number;
    category?: unknown;
    discord_bot_webhooks_enabled?: boolean;
    directory_page_enabled?: boolean;
    directory_page_chain_node_id?: number;
    namespace?: string;
    namespace_address?: string;
    redirect?: string;
    snapshot_spaces?: string[];
    include_in_digest_email?: boolean;
    profile_count?: number;
    lifetime_thread_count?: number;
    banner_text?: string;
    created_at?: string;
    updated_at?: string;
    Addresses?: CommonApi.UpdateCommunityRequestAddressesItem[];
    CommunityStakes?: CommonApi.UpdateCommunityRequestCommunityStakesItem[];
    CommunityTags?: CommonApi.UpdateCommunityRequestCommunityTagsItem[];
    ChainNode?: CommonApi.UpdateCommunityRequestChainNode;
    topics?: CommonApi.UpdateCommunityRequestTopicsItem[];
    groups?: CommonApi.UpdateCommunityRequestGroupsItem[];
    contest_managers?: CommonApi.UpdateCommunityRequestContestManagersItem[];
    community_id: string;
    featuredTopics?: string[];
    snapshot?: CommonApi.UpdateCommunityRequestSnapshot;
    transactionHash?: string;
}
