/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../../index";

/**
 * @example
 *     {
 *         thread_id: 1,
 *         links: [{
 *                 source: "snapshot",
 *                 identifier: "identifier"
 *             }]
 *     }
 */
export interface AddLinksRequest {
    thread_id: number;
    links: CommonApi.AddLinksRequestLinksItem[];
}
