/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../../index";

/**
 * @example
 *     {
 *         community_id: "community_id"
 *     }
 */
export interface GetThreadsRequest {
    limit?: string;
    /**
     * required for tRPC useInfiniteQuery hook, equivalent to page number
     */
    cursor?: string;
    order_by?: CommonApi.GetThreadsRequestOrderBy;
    order_direction?: CommonApi.GetThreadsRequestOrderDirection;
    community_id: string;
    stage?: string;
    topic_id?: number;
    includePinnedThreads?: boolean;
    from_date?: string;
    to_date?: string;
    archived?: boolean;
    contestAddress?: string;
    status?: CommonApi.GetThreadsRequestStatus;
    withXRecentComments?: number;
}
