/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const CreateThreadReactionResponseAddressRole: core.serialization.Schema<
    serializers.CreateThreadReactionResponseAddressRole.Raw,
    CommonApi.CreateThreadReactionResponseAddressRole
> = core.serialization.enum_(["admin", "moderator", "member"]);

export declare namespace CreateThreadReactionResponseAddressRole {
    type Raw = "admin" | "moderator" | "member";
}
