/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const CreateCommentReactionResponseAddressUserEmailNotificationInterval: core.serialization.Schema<
    serializers.CreateCommentReactionResponseAddressUserEmailNotificationInterval.Raw,
    CommonApi.CreateCommentReactionResponseAddressUserEmailNotificationInterval
> = core.serialization.enum_(["weekly", "never"]);

export declare namespace CreateCommentReactionResponseAddressUserEmailNotificationInterval {
    type Raw = "weekly" | "never";
}
