/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { CreateThreadReactionResponseAddress } from "./CreateThreadReactionResponseAddress";

export const CreateThreadReactionResponse: core.serialization.ObjectSchema<
    serializers.CreateThreadReactionResponse.Raw,
    CommonApi.CreateThreadReactionResponse
> = core.serialization.object({
    id: core.serialization.number().optional(),
    addressId: core.serialization.property("address_id", core.serialization.number()),
    reaction: core.serialization.stringLiteral("like"),
    threadId: core.serialization.property("thread_id", core.serialization.number().optional()),
    commentId: core.serialization.property("comment_id", core.serialization.number().optional()),
    proposalId: core.serialization.property("proposal_id", core.serialization.number().optional()),
    calculatedVotingWeight: core.serialization.property(
        "calculated_voting_weight",
        core.serialization.string().optional()
    ),
    canvasSignedData: core.serialization.property("canvas_signed_data", core.serialization.unknown().optional()),
    canvasMsgId: core.serialization.property("canvas_msg_id", core.serialization.string().optional()),
    createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date().optional()),
    address: core.serialization.property("Address", CreateThreadReactionResponseAddress.optional()),
    communityId: core.serialization.property("community_id", core.serialization.string()),
});

export declare namespace CreateThreadReactionResponse {
    interface Raw {
        id?: number | null;
        address_id: number;
        reaction: "like";
        thread_id?: number | null;
        comment_id?: number | null;
        proposal_id?: number | null;
        calculated_voting_weight?: string | null;
        canvas_signed_data?: unknown | null;
        canvas_msg_id?: string | null;
        created_at?: string | null;
        updated_at?: string | null;
        Address?: CreateThreadReactionResponseAddress.Raw | null;
        community_id: string;
    }
}
