/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const DeleteReactionResponseAddressUserEmailNotificationInterval: core.serialization.Schema<
    serializers.DeleteReactionResponseAddressUserEmailNotificationInterval.Raw,
    CommonApi.DeleteReactionResponseAddressUserEmailNotificationInterval
> = core.serialization.enum_(["weekly", "never"]);

export declare namespace DeleteReactionResponseAddressUserEmailNotificationInterval {
    type Raw = "weekly" | "never";
}
