/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CreateThreadReactionResponseAddressRole = "admin" | "moderator" | "member";

export const CreateThreadReactionResponseAddressRole = {
    Admin: "admin",
    Moderator: "moderator",
    Member: "member",
} as const;
