/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface DeleteReactionResponseAddressUser {
    id?: number;
    email?: string;
    isAdmin?: boolean;
    disableRichText?: boolean;
    emailVerified?: boolean;
    selectedCommunityId?: string;
    emailNotificationInterval?: CommonApi.DeleteReactionResponseAddressUserEmailNotificationInterval;
    promotionalEmailsEnabled?: boolean;
    isWelcomeOnboardFlowComplete?: boolean;
    profile: CommonApi.DeleteReactionResponseAddressUserProfile;
    xpPoints?: number;
    profileTags?: CommonApi.DeleteReactionResponseAddressUserProfileTagsItem[];
    apiKey?: CommonApi.DeleteReactionResponseAddressUserApiKey;
    createdAt?: Date;
    updatedAt?: Date;
}
