/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DeleteReactionResponse {
    reaction_id: number;
    canvas_signed_data?: string;
    canvas_msg_id?: string;
}
