/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const CreateThreadResponseReactionsItemAddressUserProfileBackgroundImage: core.serialization.ObjectSchema<
    serializers.CreateThreadResponseReactionsItemAddressUserProfileBackgroundImage.Raw,
    CommonApi.CreateThreadResponseReactionsItemAddressUserProfileBackgroundImage
> = core.serialization.object({
    url: core.serialization.string().optional(),
    imageBehavior: core.serialization.string().optional(),
});

export declare namespace CreateThreadResponseReactionsItemAddressUserProfileBackgroundImage {
    interface Raw {
        url?: string | null;
        imageBehavior?: string | null;
    }
}
