/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const CreateThreadResponseReactionAddressRole: core.serialization.Schema<
    serializers.CreateThreadResponseReactionAddressRole.Raw,
    CommonApi.CreateThreadResponseReactionAddressRole
> = core.serialization.enum_(["admin", "moderator", "member"]);

export declare namespace CreateThreadResponseReactionAddressRole {
    type Raw = "admin" | "moderator" | "member";
}
