/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const CreateThreadResponseReactionsItemAddressUserEmailNotificationInterval: core.serialization.Schema<
    serializers.CreateThreadResponseReactionsItemAddressUserEmailNotificationInterval.Raw,
    CommonApi.CreateThreadResponseReactionsItemAddressUserEmailNotificationInterval
> = core.serialization.enum_(["weekly", "never"]);

export declare namespace CreateThreadResponseReactionsItemAddressUserEmailNotificationInterval {
    type Raw = "weekly" | "never";
}
