/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { CreateThreadResponseReactionAddressUserEmailNotificationInterval } from "./CreateThreadResponseReactionAddressUserEmailNotificationInterval";
import { CreateThreadResponseReactionAddressUserProfile } from "./CreateThreadResponseReactionAddressUserProfile";
import { CreateThreadResponseReactionAddressUserProfileTagsItem } from "./CreateThreadResponseReactionAddressUserProfileTagsItem";
import { CreateThreadResponseReactionAddressUserApiKey } from "./CreateThreadResponseReactionAddressUserApiKey";

export const CreateThreadResponseReactionAddressUser: core.serialization.ObjectSchema<
    serializers.CreateThreadResponseReactionAddressUser.Raw,
    CommonApi.CreateThreadResponseReactionAddressUser
> = core.serialization.object({
    id: core.serialization.number().optional(),
    email: core.serialization.string().optional(),
    isAdmin: core.serialization.boolean().optional(),
    disableRichText: core.serialization.boolean().optional(),
    emailVerified: core.serialization.boolean().optional(),
    selectedCommunityId: core.serialization.property("selected_community_id", core.serialization.string().optional()),
    emailNotificationInterval: CreateThreadResponseReactionAddressUserEmailNotificationInterval.optional(),
    promotionalEmailsEnabled: core.serialization.property(
        "promotional_emails_enabled",
        core.serialization.boolean().optional()
    ),
    isWelcomeOnboardFlowComplete: core.serialization.property(
        "is_welcome_onboard_flow_complete",
        core.serialization.boolean().optional()
    ),
    profile: CreateThreadResponseReactionAddressUserProfile,
    xpPoints: core.serialization.property("xp_points", core.serialization.number().optional()),
    profileTags: core.serialization.property(
        "ProfileTags",
        core.serialization.list(CreateThreadResponseReactionAddressUserProfileTagsItem).optional()
    ),
    apiKey: core.serialization.property("ApiKey", CreateThreadResponseReactionAddressUserApiKey.optional()),
    createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date().optional()),
});

export declare namespace CreateThreadResponseReactionAddressUser {
    interface Raw {
        id?: number | null;
        email?: string | null;
        isAdmin?: boolean | null;
        disableRichText?: boolean | null;
        emailVerified?: boolean | null;
        selected_community_id?: string | null;
        emailNotificationInterval?: CreateThreadResponseReactionAddressUserEmailNotificationInterval.Raw | null;
        promotional_emails_enabled?: boolean | null;
        is_welcome_onboard_flow_complete?: boolean | null;
        profile: CreateThreadResponseReactionAddressUserProfile.Raw;
        xp_points?: number | null;
        ProfileTags?: CreateThreadResponseReactionAddressUserProfileTagsItem.Raw[] | null;
        ApiKey?: CreateThreadResponseReactionAddressUserApiKey.Raw | null;
        created_at?: string | null;
        updated_at?: string | null;
    }
}
