/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetThreadsResponseThreadsItemReactionAddressUserProfileTagsItemCreatedAt: core.serialization.Schema<
    serializers.GetThreadsResponseThreadsItemReactionAddressUserProfileTagsItemCreatedAt.Raw,
    CommonApi.GetThreadsResponseThreadsItemReactionAddressUserProfileTagsItemCreatedAt
> = core.serialization.undiscriminatedUnion([core.serialization.date(), core.serialization.string()]);

export declare namespace GetThreadsResponseThreadsItemReactionAddressUserProfileTagsItemCreatedAt {
    type Raw = string | string;
}
