/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetThreadsResponseThreadsItemThreadVersionHistoriesItemTimestamp } from "./GetThreadsResponseThreadsItemThreadVersionHistoriesItemTimestamp";

export const GetThreadsResponseThreadsItemThreadVersionHistoriesItem: core.serialization.ObjectSchema<
    serializers.GetThreadsResponseThreadsItemThreadVersionHistoriesItem.Raw,
    CommonApi.GetThreadsResponseThreadsItemThreadVersionHistoriesItem
> = core.serialization.object({
    id: core.serialization.number(),
    threadId: core.serialization.property("thread_id", core.serialization.number()),
    address: core.serialization.string(),
    body: core.serialization.string(),
    timestamp: GetThreadsResponseThreadsItemThreadVersionHistoriesItemTimestamp,
    contentUrl: core.serialization.property("content_url", core.serialization.string().optional()),
});

export declare namespace GetThreadsResponseThreadsItemThreadVersionHistoriesItem {
    interface Raw {
        id: number;
        thread_id: number;
        address: string;
        body: string;
        timestamp: GetThreadsResponseThreadsItemThreadVersionHistoriesItemTimestamp.Raw;
        content_url?: string | null;
    }
}
