/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetThreadsResponseThreadsItemReactionsItemAddressUserEmailNotificationInterval: core.serialization.Schema<
    serializers.GetThreadsResponseThreadsItemReactionsItemAddressUserEmailNotificationInterval.Raw,
    CommonApi.GetThreadsResponseThreadsItemReactionsItemAddressUserEmailNotificationInterval
> = core.serialization.enum_(["weekly", "never"]);

export declare namespace GetThreadsResponseThreadsItemReactionsItemAddressUserEmailNotificationInterval {
    type Raw = "weekly" | "never";
}
