/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetThreadsResponseThreadsItemAddressUserEmailNotificationInterval } from "./GetThreadsResponseThreadsItemAddressUserEmailNotificationInterval";
import { GetThreadsResponseThreadsItemAddressUserProfile } from "./GetThreadsResponseThreadsItemAddressUserProfile";
import { GetThreadsResponseThreadsItemAddressUserProfileTagsItem } from "./GetThreadsResponseThreadsItemAddressUserProfileTagsItem";
import { GetThreadsResponseThreadsItemAddressUserCreatedAt } from "./GetThreadsResponseThreadsItemAddressUserCreatedAt";
import { GetThreadsResponseThreadsItemAddressUserUpdatedAt } from "./GetThreadsResponseThreadsItemAddressUserUpdatedAt";

export const GetThreadsResponseThreadsItemAddressUser: core.serialization.ObjectSchema<
    serializers.GetThreadsResponseThreadsItemAddressUser.Raw,
    CommonApi.GetThreadsResponseThreadsItemAddressUser
> = core.serialization.object({
    id: core.serialization.number(),
    email: core.serialization.string().optional(),
    isAdmin: core.serialization.boolean().optional(),
    disableRichText: core.serialization.boolean().optional(),
    emailVerified: core.serialization.boolean().optional(),
    selectedCommunityId: core.serialization.property("selected_community_id", core.serialization.string().optional()),
    emailNotificationInterval: GetThreadsResponseThreadsItemAddressUserEmailNotificationInterval.optional(),
    promotionalEmailsEnabled: core.serialization.property(
        "promotional_emails_enabled",
        core.serialization.boolean().optional()
    ),
    isWelcomeOnboardFlowComplete: core.serialization.property(
        "is_welcome_onboard_flow_complete",
        core.serialization.boolean().optional()
    ),
    profile: GetThreadsResponseThreadsItemAddressUserProfile,
    xpPoints: core.serialization.property("xp_points", core.serialization.number().optional()),
    profileTags: core.serialization.property(
        "ProfileTags",
        core.serialization.list(GetThreadsResponseThreadsItemAddressUserProfileTagsItem).optional()
    ),
    apiKey: core.serialization.property("ApiKey", core.serialization.unknown().optional()),
    createdAt: core.serialization.property("created_at", GetThreadsResponseThreadsItemAddressUserCreatedAt.optional()),
    updatedAt: core.serialization.property("updated_at", GetThreadsResponseThreadsItemAddressUserUpdatedAt.optional()),
});

export declare namespace GetThreadsResponseThreadsItemAddressUser {
    interface Raw {
        id: number;
        email?: string | null;
        isAdmin?: boolean | null;
        disableRichText?: boolean | null;
        emailVerified?: boolean | null;
        selected_community_id?: string | null;
        emailNotificationInterval?: GetThreadsResponseThreadsItemAddressUserEmailNotificationInterval.Raw | null;
        promotional_emails_enabled?: boolean | null;
        is_welcome_onboard_flow_complete?: boolean | null;
        profile: GetThreadsResponseThreadsItemAddressUserProfile.Raw;
        xp_points?: number | null;
        ProfileTags?: GetThreadsResponseThreadsItemAddressUserProfileTagsItem.Raw[] | null;
        ApiKey?: unknown | null;
        created_at?: GetThreadsResponseThreadsItemAddressUserCreatedAt.Raw | null;
        updated_at?: GetThreadsResponseThreadsItemAddressUserUpdatedAt.Raw | null;
    }
}
