/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetThreadsResponseThreadsItemCollaboratorsItemUserEmailNotificationInterval: core.serialization.Schema<
    serializers.GetThreadsResponseThreadsItemCollaboratorsItemUserEmailNotificationInterval.Raw,
    CommonApi.GetThreadsResponseThreadsItemCollaboratorsItemUserEmailNotificationInterval
> = core.serialization.enum_(["weekly", "never"]);

export declare namespace GetThreadsResponseThreadsItemCollaboratorsItemUserEmailNotificationInterval {
    type Raw = "weekly" | "never";
}
