/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetThreadsResponseThreadsItemReactionAddressUserEmailNotificationInterval: core.serialization.Schema<
    serializers.GetThreadsResponseThreadsItemReactionAddressUserEmailNotificationInterval.Raw,
    CommonApi.GetThreadsResponseThreadsItemReactionAddressUserEmailNotificationInterval
> = core.serialization.enum_(["weekly", "never"]);

export declare namespace GetThreadsResponseThreadsItemReactionAddressUserEmailNotificationInterval {
    type Raw = "weekly" | "never";
}
