/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetThreadsResponseThreadsItemCommentsItemUpdatedAt: core.serialization.Schema<
    serializers.GetThreadsResponseThreadsItemCommentsItemUpdatedAt.Raw,
    CommonApi.GetThreadsResponseThreadsItemCommentsItemUpdatedAt
> = core.serialization.undiscriminatedUnion([core.serialization.date(), core.serialization.string()]);

export declare namespace GetThreadsResponseThreadsItemCommentsItemUpdatedAt {
    type Raw = string | string;
}
