/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetThreadsResponseThreadsItemCommentsItemAddressLastActive: core.serialization.Schema<
    serializers.GetThreadsResponseThreadsItemCommentsItemAddressLastActive.Raw,
    CommonApi.GetThreadsResponseThreadsItemCommentsItemAddressLastActive
> = core.serialization.undiscriminatedUnion([core.serialization.date(), core.serialization.string()]);

export declare namespace GetThreadsResponseThreadsItemCommentsItemAddressLastActive {
    type Raw = string | string;
}
