/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetThreadsResponseThreadsItemCommentsItemCreatedAt } from "./GetThreadsResponseThreadsItemCommentsItemCreatedAt";
import { GetThreadsResponseThreadsItemCommentsItemUpdatedAt } from "./GetThreadsResponseThreadsItemCommentsItemUpdatedAt";
import { GetThreadsResponseThreadsItemCommentsItemDeletedAt } from "./GetThreadsResponseThreadsItemCommentsItemDeletedAt";
import { GetThreadsResponseThreadsItemCommentsItemMarkedAsSpamAt } from "./GetThreadsResponseThreadsItemCommentsItemMarkedAsSpamAt";
import { GetThreadsResponseThreadsItemCommentsItemDiscordMeta } from "./GetThreadsResponseThreadsItemCommentsItemDiscordMeta";
import { GetThreadsResponseThreadsItemCommentsItemAddress } from "./GetThreadsResponseThreadsItemCommentsItemAddress";
import { GetThreadsResponseThreadsItemCommentsItemReaction } from "./GetThreadsResponseThreadsItemCommentsItemReaction";

export const GetThreadsResponseThreadsItemCommentsItem: core.serialization.ObjectSchema<
    serializers.GetThreadsResponseThreadsItemCommentsItem.Raw,
    CommonApi.GetThreadsResponseThreadsItemCommentsItem
> = core.serialization.object({
    id: core.serialization.number(),
    threadId: core.serialization.property("thread_id", core.serialization.number()),
    addressId: core.serialization.property("address_id", core.serialization.number()),
    body: core.serialization.string(),
    parentId: core.serialization.property("parent_id", core.serialization.string().optional()),
    contentUrl: core.serialization.property("content_url", core.serialization.string().optional()),
    canvasSignedData: core.serialization.property("canvas_signed_data", core.serialization.string().optional()),
    canvasMsgId: core.serialization.property("canvas_msg_id", core.serialization.string().optional()),
    createdBy: core.serialization.property("created_by", core.serialization.string().optional()),
    createdAt: core.serialization.property("created_at", GetThreadsResponseThreadsItemCommentsItemCreatedAt.optional()),
    updatedAt: core.serialization.property("updated_at", GetThreadsResponseThreadsItemCommentsItemUpdatedAt.optional()),
    deletedAt: core.serialization.property("deleted_at", GetThreadsResponseThreadsItemCommentsItemDeletedAt.optional()),
    markedAsSpamAt: core.serialization.property(
        "marked_as_spam_at",
        GetThreadsResponseThreadsItemCommentsItemMarkedAsSpamAt.optional()
    ),
    discordMeta: core.serialization.property(
        "discord_meta",
        GetThreadsResponseThreadsItemCommentsItemDiscordMeta.optional()
    ),
    reactionCount: core.serialization.property("reaction_count", core.serialization.number()),
    reactionWeightsSum: core.serialization.property("reaction_weights_sum", core.serialization.string().optional()),
    search: core.serialization.unknown().optional(),
    address: core.serialization.property("Address", GetThreadsResponseThreadsItemCommentsItemAddress.optional()),
    thread: core.serialization.property("Thread", core.serialization.unknown().optional()),
    reaction: core.serialization.property("Reaction", GetThreadsResponseThreadsItemCommentsItemReaction.optional()),
    commentVersionHistories: core.serialization.property(
        "CommentVersionHistories",
        core.serialization.unknown().optional()
    ),
    address: core.serialization.string(),
    profileName: core.serialization.property("profile_name", core.serialization.string().optional()),
    profileAvatar: core.serialization.property("profile_avatar", core.serialization.string().optional()),
    userId: core.serialization.property("user_id", core.serialization.number()),
});

export declare namespace GetThreadsResponseThreadsItemCommentsItem {
    interface Raw {
        id: number;
        thread_id: number;
        address_id: number;
        body: string;
        parent_id?: string | null;
        content_url?: string | null;
        canvas_signed_data?: string | null;
        canvas_msg_id?: string | null;
        created_by?: string | null;
        created_at?: GetThreadsResponseThreadsItemCommentsItemCreatedAt.Raw | null;
        updated_at?: GetThreadsResponseThreadsItemCommentsItemUpdatedAt.Raw | null;
        deleted_at?: GetThreadsResponseThreadsItemCommentsItemDeletedAt.Raw | null;
        marked_as_spam_at?: GetThreadsResponseThreadsItemCommentsItemMarkedAsSpamAt.Raw | null;
        discord_meta?: GetThreadsResponseThreadsItemCommentsItemDiscordMeta.Raw | null;
        reaction_count: number;
        reaction_weights_sum?: string | null;
        search?: unknown | null;
        Address?: GetThreadsResponseThreadsItemCommentsItemAddress.Raw | null;
        Thread?: unknown | null;
        Reaction?: GetThreadsResponseThreadsItemCommentsItemReaction.Raw | null;
        CommentVersionHistories?: unknown | null;
        address: string;
        profile_name?: string | null;
        profile_avatar?: string | null;
        user_id: number;
    }
}
