/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetThreadsResponseThreadsItemReactionsItemAddressLastActive: core.serialization.Schema<
    serializers.GetThreadsResponseThreadsItemReactionsItemAddressLastActive.Raw,
    CommonApi.GetThreadsResponseThreadsItemReactionsItemAddressLastActive
> = core.serialization.undiscriminatedUnion([core.serialization.date(), core.serialization.string()]);

export declare namespace GetThreadsResponseThreadsItemReactionsItemAddressLastActive {
    type Raw = string | string;
}
