/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetThreadsResponseThreadsItemCollaboratorsItemUserCreatedAt: core.serialization.Schema<
    serializers.GetThreadsResponseThreadsItemCollaboratorsItemUserCreatedAt.Raw,
    CommonApi.GetThreadsResponseThreadsItemCollaboratorsItemUserCreatedAt
> = core.serialization.undiscriminatedUnion([core.serialization.date(), core.serialization.string()]);

export declare namespace GetThreadsResponseThreadsItemCollaboratorsItemUserCreatedAt {
    type Raw = string | string;
}
