/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetThreadsResponseThreadsItemLinksItemSource } from "./GetThreadsResponseThreadsItemLinksItemSource";

export const GetThreadsResponseThreadsItemLinksItem: core.serialization.ObjectSchema<
    serializers.GetThreadsResponseThreadsItemLinksItem.Raw,
    CommonApi.GetThreadsResponseThreadsItemLinksItem
> = core.serialization.object({
    source: GetThreadsResponseThreadsItemLinksItemSource,
    identifier: core.serialization.string(),
    title: core.serialization.string().optional(),
});

export declare namespace GetThreadsResponseThreadsItemLinksItem {
    interface Raw {
        source: GetThreadsResponseThreadsItemLinksItemSource.Raw;
        identifier: string;
        title?: string | null;
    }
}
