/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetThreadsResponseThreadsItemAddressRole: core.serialization.Schema<
    serializers.GetThreadsResponseThreadsItemAddressRole.Raw,
    CommonApi.GetThreadsResponseThreadsItemAddressRole
> = core.serialization.enum_(["admin", "moderator", "member"]);

export declare namespace GetThreadsResponseThreadsItemAddressRole {
    type Raw = "admin" | "moderator" | "member";
}
