/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetThreadsResponseThreadsItemReactionsItemAddressRole: core.serialization.Schema<
    serializers.GetThreadsResponseThreadsItemReactionsItemAddressRole.Raw,
    CommonApi.GetThreadsResponseThreadsItemReactionsItemAddressRole
> = core.serialization.enum_(["admin", "moderator", "member"]);

export declare namespace GetThreadsResponseThreadsItemReactionsItemAddressRole {
    type Raw = "admin" | "moderator" | "member";
}
