/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetThreadsResponseThreadsItemAssociatedContestsItemContestManager } from "./GetThreadsResponseThreadsItemAssociatedContestsItemContestManager";
import { GetThreadsResponseThreadsItemAssociatedContestsItemStartTime } from "./GetThreadsResponseThreadsItemAssociatedContestsItemStartTime";
import { GetThreadsResponseThreadsItemAssociatedContestsItemEndTime } from "./GetThreadsResponseThreadsItemAssociatedContestsItemEndTime";
import { GetThreadsResponseThreadsItemAssociatedContestsItemScoreItem } from "./GetThreadsResponseThreadsItemAssociatedContestsItemScoreItem";

export const GetThreadsResponseThreadsItemAssociatedContestsItem: core.serialization.ObjectSchema<
    serializers.GetThreadsResponseThreadsItemAssociatedContestsItem.Raw,
    CommonApi.GetThreadsResponseThreadsItemAssociatedContestsItem
> = core.serialization.object({
    contestManager: core.serialization.property(
        "ContestManager",
        GetThreadsResponseThreadsItemAssociatedContestsItemContestManager
    ),
    contestId: core.serialization.property("contest_id", core.serialization.number()),
    contestAddress: core.serialization.property("contest_address", core.serialization.string()),
    startTime: core.serialization.property("start_time", GetThreadsResponseThreadsItemAssociatedContestsItemStartTime),
    endTime: core.serialization.property("end_time", GetThreadsResponseThreadsItemAssociatedContestsItemEndTime),
    score: core.serialization.list(GetThreadsResponseThreadsItemAssociatedContestsItemScoreItem),
    contestName: core.serialization.property("contest_name", core.serialization.string().optional()),
    contestInterval: core.serialization.property("contest_interval", core.serialization.number().optional()),
    contentId: core.serialization.property("content_id", core.serialization.number().optional()),
    contestCancelled: core.serialization.property("contest_cancelled", core.serialization.boolean().optional()),
    threadId: core.serialization.property("thread_id", core.serialization.number().optional()),
});

export declare namespace GetThreadsResponseThreadsItemAssociatedContestsItem {
    interface Raw {
        ContestManager: GetThreadsResponseThreadsItemAssociatedContestsItemContestManager.Raw;
        contest_id: number;
        contest_address: string;
        start_time: GetThreadsResponseThreadsItemAssociatedContestsItemStartTime.Raw;
        end_time: GetThreadsResponseThreadsItemAssociatedContestsItemEndTime.Raw;
        score: GetThreadsResponseThreadsItemAssociatedContestsItemScoreItem.Raw[];
        contest_name?: string | null;
        contest_interval?: number | null;
        content_id?: number | null;
        contest_cancelled?: boolean | null;
        thread_id?: number | null;
    }
}
