/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetThreadsResponseThreadsItemCommentsItemReactionAddressWalletId: core.serialization.Schema<
    serializers.GetThreadsResponseThreadsItemCommentsItemReactionAddressWalletId.Raw,
    CommonApi.GetThreadsResponseThreadsItemCommentsItemReactionAddressWalletId
> = core.serialization.enum_([
    "magic",
    "polkadot",
    "metamask",
    "walletconnect",
    "keplr-ethereum",
    "keplr",
    "leap",
    "near",
    "terrastation",
    "terra-walletconnect",
    "cosm-metamask",
    "phantom",
    "coinbase",
]);

export declare namespace GetThreadsResponseThreadsItemCommentsItemReactionAddressWalletId {
    type Raw =
        | "magic"
        | "polkadot"
        | "metamask"
        | "walletconnect"
        | "keplr-ethereum"
        | "keplr"
        | "leap"
        | "near"
        | "terrastation"
        | "terra-walletconnect"
        | "cosm-metamask"
        | "phantom"
        | "coinbase";
}
