/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetThreadsResponseThreadsItemCommentsItemAddressCreatedAt: core.serialization.Schema<
    serializers.GetThreadsResponseThreadsItemCommentsItemAddressCreatedAt.Raw,
    CommonApi.GetThreadsResponseThreadsItemCommentsItemAddressCreatedAt
> = core.serialization.undiscriminatedUnion([core.serialization.date(), core.serialization.string()]);

export declare namespace GetThreadsResponseThreadsItemCommentsItemAddressCreatedAt {
    type Raw = string | string;
}
