/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetThreadsResponseThreadsItemTopicActiveContestManagersItemContentItemAction: core.serialization.Schema<
    serializers.GetThreadsResponseThreadsItemTopicActiveContestManagersItemContentItemAction.Raw,
    CommonApi.GetThreadsResponseThreadsItemTopicActiveContestManagersItemContentItemAction
> = core.serialization.enum_(["added", "upvoted"]);

export declare namespace GetThreadsResponseThreadsItemTopicActiveContestManagersItemContentItemAction {
    type Raw = "added" | "upvoted";
}
