/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetThreadsResponseThreadsItemReactionsItemAddressCreatedAt: core.serialization.Schema<
    serializers.GetThreadsResponseThreadsItemReactionsItemAddressCreatedAt.Raw,
    CommonApi.GetThreadsResponseThreadsItemReactionsItemAddressCreatedAt
> = core.serialization.undiscriminatedUnion([core.serialization.date(), core.serialization.string()]);

export declare namespace GetThreadsResponseThreadsItemReactionsItemAddressCreatedAt {
    type Raw = string | string;
}
