/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetThreadsResponseThreadsItemAddressUserEmailNotificationInterval: core.serialization.Schema<
    serializers.GetThreadsResponseThreadsItemAddressUserEmailNotificationInterval.Raw,
    CommonApi.GetThreadsResponseThreadsItemAddressUserEmailNotificationInterval
> = core.serialization.enum_(["weekly", "never"]);

export declare namespace GetThreadsResponseThreadsItemAddressUserEmailNotificationInterval {
    type Raw = "weekly" | "never";
}
