/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItemUpdatedAt: core.serialization.Schema<
    serializers.GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItemUpdatedAt.Raw,
    CommonApi.GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItemUpdatedAt
> = core.serialization.undiscriminatedUnion([core.serialization.date(), core.serialization.string()]);

export declare namespace GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItemUpdatedAt {
    type Raw = string | string;
}
