/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetThreadsResponseThreadsItemReactionAddressUserProfileTagsItemCreatedAt } from "./GetThreadsResponseThreadsItemReactionAddressUserProfileTagsItemCreatedAt";
import { GetThreadsResponseThreadsItemReactionAddressUserProfileTagsItemUpdatedAt } from "./GetThreadsResponseThreadsItemReactionAddressUserProfileTagsItemUpdatedAt";
import { GetThreadsResponseThreadsItemReactionAddressUserProfileTagsItemTag } from "./GetThreadsResponseThreadsItemReactionAddressUserProfileTagsItemTag";

export const GetThreadsResponseThreadsItemReactionAddressUserProfileTagsItem: core.serialization.ObjectSchema<
    serializers.GetThreadsResponseThreadsItemReactionAddressUserProfileTagsItem.Raw,
    CommonApi.GetThreadsResponseThreadsItemReactionAddressUserProfileTagsItem
> = core.serialization.object({
    userId: core.serialization.property("user_id", core.serialization.number()),
    tagId: core.serialization.property("tag_id", core.serialization.number()),
    createdAt: core.serialization.property(
        "created_at",
        GetThreadsResponseThreadsItemReactionAddressUserProfileTagsItemCreatedAt.optional()
    ),
    updatedAt: core.serialization.property(
        "updated_at",
        GetThreadsResponseThreadsItemReactionAddressUserProfileTagsItemUpdatedAt.optional()
    ),
    tag: core.serialization.property(
        "Tag",
        GetThreadsResponseThreadsItemReactionAddressUserProfileTagsItemTag.optional()
    ),
});

export declare namespace GetThreadsResponseThreadsItemReactionAddressUserProfileTagsItem {
    interface Raw {
        user_id: number;
        tag_id: number;
        created_at?: GetThreadsResponseThreadsItemReactionAddressUserProfileTagsItemCreatedAt.Raw | null;
        updated_at?: GetThreadsResponseThreadsItemReactionAddressUserProfileTagsItemUpdatedAt.Raw | null;
        Tag?: GetThreadsResponseThreadsItemReactionAddressUserProfileTagsItemTag.Raw | null;
    }
}
