/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetThreadsResponseThreadsItemCollaboratorsItemUserProfileTagsItemCreatedAt } from "./GetThreadsResponseThreadsItemCollaboratorsItemUserProfileTagsItemCreatedAt";
import { GetThreadsResponseThreadsItemCollaboratorsItemUserProfileTagsItemUpdatedAt } from "./GetThreadsResponseThreadsItemCollaboratorsItemUserProfileTagsItemUpdatedAt";
import { GetThreadsResponseThreadsItemCollaboratorsItemUserProfileTagsItemTag } from "./GetThreadsResponseThreadsItemCollaboratorsItemUserProfileTagsItemTag";

export const GetThreadsResponseThreadsItemCollaboratorsItemUserProfileTagsItem: core.serialization.ObjectSchema<
    serializers.GetThreadsResponseThreadsItemCollaboratorsItemUserProfileTagsItem.Raw,
    CommonApi.GetThreadsResponseThreadsItemCollaboratorsItemUserProfileTagsItem
> = core.serialization.object({
    userId: core.serialization.property("user_id", core.serialization.number()),
    tagId: core.serialization.property("tag_id", core.serialization.number()),
    createdAt: core.serialization.property(
        "created_at",
        GetThreadsResponseThreadsItemCollaboratorsItemUserProfileTagsItemCreatedAt.optional()
    ),
    updatedAt: core.serialization.property(
        "updated_at",
        GetThreadsResponseThreadsItemCollaboratorsItemUserProfileTagsItemUpdatedAt.optional()
    ),
    tag: core.serialization.property(
        "Tag",
        GetThreadsResponseThreadsItemCollaboratorsItemUserProfileTagsItemTag.optional()
    ),
});

export declare namespace GetThreadsResponseThreadsItemCollaboratorsItemUserProfileTagsItem {
    interface Raw {
        user_id: number;
        tag_id: number;
        created_at?: GetThreadsResponseThreadsItemCollaboratorsItemUserProfileTagsItemCreatedAt.Raw | null;
        updated_at?: GetThreadsResponseThreadsItemCollaboratorsItemUserProfileTagsItemUpdatedAt.Raw | null;
        Tag?: GetThreadsResponseThreadsItemCollaboratorsItemUserProfileTagsItemTag.Raw | null;
    }
}
