/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetThreadsResponseThreadsItemAddressLastActive: core.serialization.Schema<
    serializers.GetThreadsResponseThreadsItemAddressLastActive.Raw,
    CommonApi.GetThreadsResponseThreadsItemAddressLastActive
> = core.serialization.undiscriminatedUnion([core.serialization.date(), core.serialization.string()]);

export declare namespace GetThreadsResponseThreadsItemAddressLastActive {
    type Raw = string | string;
}
