/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetThreadsResponseThreadsItemCommentsItemReactionAddressCreatedAt: core.serialization.Schema<
    serializers.GetThreadsResponseThreadsItemCommentsItemReactionAddressCreatedAt.Raw,
    CommonApi.GetThreadsResponseThreadsItemCommentsItemReactionAddressCreatedAt
> = core.serialization.undiscriminatedUnion([core.serialization.date(), core.serialization.string()]);

export declare namespace GetThreadsResponseThreadsItemCommentsItemReactionAddressCreatedAt {
    type Raw = string | string;
}
