/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItemCreatedAt } from "./GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItemCreatedAt";
import { GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItemUpdatedAt } from "./GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItemUpdatedAt";
import { GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItemTag } from "./GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItemTag";

export const GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItem: core.serialization.ObjectSchema<
    serializers.GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItem.Raw,
    CommonApi.GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItem
> = core.serialization.object({
    userId: core.serialization.property("user_id", core.serialization.number()),
    tagId: core.serialization.property("tag_id", core.serialization.number()),
    createdAt: core.serialization.property(
        "created_at",
        GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItemCreatedAt.optional()
    ),
    updatedAt: core.serialization.property(
        "updated_at",
        GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItemUpdatedAt.optional()
    ),
    tag: core.serialization.property(
        "Tag",
        GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItemTag.optional()
    ),
});

export declare namespace GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItem {
    interface Raw {
        user_id: number;
        tag_id: number;
        created_at?: GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItemCreatedAt.Raw | null;
        updated_at?: GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItemUpdatedAt.Raw | null;
        Tag?: GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItemTag.Raw | null;
    }
}
