/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetThreadsResponseThreadsItemDeletedAt: core.serialization.Schema<
    serializers.GetThreadsResponseThreadsItemDeletedAt.Raw,
    CommonApi.GetThreadsResponseThreadsItemDeletedAt
> = core.serialization.undiscriminatedUnion([core.serialization.date(), core.serialization.string()]);

export declare namespace GetThreadsResponseThreadsItemDeletedAt {
    type Raw = string | string;
}
