/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetThreadsResponseThreadsItemReactionAddressUserProfileBackgroundImage: core.serialization.ObjectSchema<
    serializers.GetThreadsResponseThreadsItemReactionAddressUserProfileBackgroundImage.Raw,
    CommonApi.GetThreadsResponseThreadsItemReactionAddressUserProfileBackgroundImage
> = core.serialization.object({
    url: core.serialization.string().optional(),
    imageBehavior: core.serialization.string().optional(),
});

export declare namespace GetThreadsResponseThreadsItemReactionAddressUserProfileBackgroundImage {
    interface Raw {
        url?: string | null;
        imageBehavior?: string | null;
    }
}
