/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetThreadsResponseThreadsItemContestActionsItemContestEndTime: core.serialization.Schema<
    serializers.GetThreadsResponseThreadsItemContestActionsItemContestEndTime.Raw,
    CommonApi.GetThreadsResponseThreadsItemContestActionsItemContestEndTime
> = core.serialization.undiscriminatedUnion([core.serialization.date(), core.serialization.string()]);

export declare namespace GetThreadsResponseThreadsItemContestActionsItemContestEndTime {
    type Raw = string | string;
}
