/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetThreadsResponseThreadsItemReactionLastActive: core.serialization.Schema<
    serializers.GetThreadsResponseThreadsItemReactionLastActive.Raw,
    CommonApi.GetThreadsResponseThreadsItemReactionLastActive
> = core.serialization.undiscriminatedUnion([core.serialization.date(), core.serialization.string()]);

export declare namespace GetThreadsResponseThreadsItemReactionLastActive {
    type Raw = string | string;
}
