/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetThreadsResponseThreadsItemAddressUserUpdatedAt: core.serialization.Schema<
    serializers.GetThreadsResponseThreadsItemAddressUserUpdatedAt.Raw,
    CommonApi.GetThreadsResponseThreadsItemAddressUserUpdatedAt
> = core.serialization.undiscriminatedUnion([core.serialization.date(), core.serialization.string()]);

export declare namespace GetThreadsResponseThreadsItemAddressUserUpdatedAt {
    type Raw = string | string;
}
