/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetThreadsResponseThreadsItemCollaboratorsItemCreatedAt: core.serialization.Schema<
    serializers.GetThreadsResponseThreadsItemCollaboratorsItemCreatedAt.Raw,
    CommonApi.GetThreadsResponseThreadsItemCollaboratorsItemCreatedAt
> = core.serialization.undiscriminatedUnion([core.serialization.date(), core.serialization.string()]);

export declare namespace GetThreadsResponseThreadsItemCollaboratorsItemCreatedAt {
    type Raw = string | string;
}
