/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const UpdateThreadResponseReactionAddressUserEmailNotificationInterval: core.serialization.Schema<
    serializers.UpdateThreadResponseReactionAddressUserEmailNotificationInterval.Raw,
    CommonApi.UpdateThreadResponseReactionAddressUserEmailNotificationInterval
> = core.serialization.enum_(["weekly", "never"]);

export declare namespace UpdateThreadResponseReactionAddressUserEmailNotificationInterval {
    type Raw = "weekly" | "never";
}
