/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const UpdateThreadResponseCollaboratorsItemUserEmailNotificationInterval: core.serialization.Schema<
    serializers.UpdateThreadResponseCollaboratorsItemUserEmailNotificationInterval.Raw,
    CommonApi.UpdateThreadResponseCollaboratorsItemUserEmailNotificationInterval
> = core.serialization.enum_(["weekly", "never"]);

export declare namespace UpdateThreadResponseCollaboratorsItemUserEmailNotificationInterval {
    type Raw = "weekly" | "never";
}
