/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const UpdateThreadRequestCollaborators: core.serialization.ObjectSchema<
    serializers.UpdateThreadRequestCollaborators.Raw,
    CommonApi.UpdateThreadRequestCollaborators
> = core.serialization.object({
    toAdd: core.serialization.list(core.serialization.number()).optional(),
    toRemove: core.serialization.list(core.serialization.number()).optional(),
});

export declare namespace UpdateThreadRequestCollaborators {
    interface Raw {
        toAdd?: number[] | null;
        toRemove?: number[] | null;
    }
}
