/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         community_id: "community_id",
 *         reaction_id: 1
 *     }
 */
export interface DeleteReactionRequest {
    community_id: string;
    reaction_id: number;
    canvas_signed_data?: string;
    canvas_msg_id?: string;
}
