/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetAllContestsResponseItemContestsItemScoreItem } from "./GetAllContestsResponseItemContestsItemScoreItem";
import { GetAllContestsResponseItemContestsItemActionsItem } from "./GetAllContestsResponseItemContestsItemActionsItem";

export const GetAllContestsResponseItemContestsItem: core.serialization.ObjectSchema<
    serializers.GetAllContestsResponseItemContestsItem.Raw,
    CommonApi.GetAllContestsResponseItemContestsItem
> = core.serialization.object({
    contestId: core.serialization.property("contest_id", core.serialization.number()),
    startTime: core.serialization.property("start_time", core.serialization.date()),
    endTime: core.serialization.property("end_time", core.serialization.date()),
    scoreUpdatedAt: core.serialization.property("score_updated_at", core.serialization.date().optional()),
    score: core.serialization.list(GetAllContestsResponseItemContestsItemScoreItem).optional(),
    actions: core.serialization.list(GetAllContestsResponseItemContestsItemActionsItem).optional(),
});

export declare namespace GetAllContestsResponseItemContestsItem {
    interface Raw {
        contest_id: number;
        start_time: string;
        end_time: string;
        score_updated_at?: string | null;
        score?: GetAllContestsResponseItemContestsItemScoreItem.Raw[] | null;
        actions?: GetAllContestsResponseItemContestsItemActionsItem.Raw[] | null;
    }
}
