/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as CommonApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const DeleteCommentRequest: core.serialization.Schema<
    serializers.DeleteCommentRequest.Raw,
    CommonApi.DeleteCommentRequest
> = core.serialization.object({
    commentId: core.serialization.property("comment_id", core.serialization.number()),
});

export declare namespace DeleteCommentRequest {
    interface Raw {
        comment_id: number;
    }
}
