/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetGlobalActivityRequestOrderDirection: core.serialization.Schema<
    serializers.GetGlobalActivityRequestOrderDirection.Raw,
    CommonApi.GetGlobalActivityRequestOrderDirection
> = core.serialization.enum_(["ASC", "DESC"]);

export declare namespace GetGlobalActivityRequestOrderDirection {
    type Raw = "ASC" | "DESC";
}
