/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetGlobalActivityResponseResultsItemDiscordMetaUser: core.serialization.ObjectSchema<
    serializers.GetGlobalActivityResponseResultsItemDiscordMetaUser.Raw,
    CommonApi.GetGlobalActivityResponseResultsItemDiscordMetaUser
> = core.serialization.object({
    id: core.serialization.string(),
    username: core.serialization.string(),
});

export declare namespace GetGlobalActivityResponseResultsItemDiscordMetaUser {
    interface Raw {
        id: string;
        username: string;
    }
}
