/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetUserActivityResponseResultsItemDiscordMetaUser } from "./GetUserActivityResponseResultsItemDiscordMetaUser";

export const GetUserActivityResponseResultsItemDiscordMeta: core.serialization.ObjectSchema<
    serializers.GetUserActivityResponseResultsItemDiscordMeta.Raw,
    CommonApi.GetUserActivityResponseResultsItemDiscordMeta
> = core.serialization.object({
    user: GetUserActivityResponseResultsItemDiscordMetaUser,
    channelId: core.serialization.property("channel_id", core.serialization.string()),
    messageId: core.serialization.property("message_id", core.serialization.string()),
});

export declare namespace GetUserActivityResponseResultsItemDiscordMeta {
    interface Raw {
        user: GetUserActivityResponseResultsItemDiscordMetaUser.Raw;
        channel_id: string;
        message_id: string;
    }
}
