/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetUserActivityResponseResultsItemTopic: core.serialization.ObjectSchema<
    serializers.GetUserActivityResponseResultsItemTopic.Raw,
    CommonApi.GetUserActivityResponseResultsItemTopic
> = core.serialization.object({
    id: core.serialization.number(),
    name: core.serialization.string(),
    description: core.serialization.string(),
});

export declare namespace GetUserActivityResponseResultsItemTopic {
    interface Raw {
        id: number;
        name: string;
        description: string;
    }
}
