/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetUserActivityResponseResultsItem } from "./GetUserActivityResponseResultsItem";

export const GetUserActivityResponse: core.serialization.ObjectSchema<
    serializers.GetUserActivityResponse.Raw,
    CommonApi.GetUserActivityResponse
> = core.serialization.object({
    limit: core.serialization.number(),
    page: core.serialization.number(),
    totalPages: core.serialization.number(),
    totalResults: core.serialization.number(),
    results: core.serialization.list(GetUserActivityResponseResultsItem),
});

export declare namespace GetUserActivityResponse {
    interface Raw {
        limit: number;
        page: number;
        totalPages: number;
        totalResults: number;
        results: GetUserActivityResponseResultsItem.Raw[];
    }
}
