/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as CommonApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { CreateGroupRequestMetadata } from "../../types/CreateGroupRequestMetadata";
import { CreateGroupRequestRequirementsItem } from "../../types/CreateGroupRequestRequirementsItem";
import { CreateGroupRequestTopicsItem } from "../../types/CreateGroupRequestTopicsItem";

export const CreateGroupRequest: core.serialization.Schema<
    serializers.CreateGroupRequest.Raw,
    CommonApi.CreateGroupRequest
> = core.serialization.object({
    communityId: core.serialization.property("community_id", core.serialization.string()),
    metadata: CreateGroupRequestMetadata,
    requirements: core.serialization.list(CreateGroupRequestRequirementsItem).optional(),
    topics: core.serialization.list(CreateGroupRequestTopicsItem).optional(),
});

export declare namespace CreateGroupRequest {
    interface Raw {
        community_id: string;
        metadata: CreateGroupRequestMetadata.Raw;
        requirements?: CreateGroupRequestRequirementsItem.Raw[] | null;
        topics?: CreateGroupRequestTopicsItem.Raw[] | null;
    }
}
