/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as CommonApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const DeleteGroupRequest: core.serialization.Schema<
    serializers.DeleteGroupRequest.Raw,
    CommonApi.DeleteGroupRequest
> = core.serialization.object({
    communityId: core.serialization.property("community_id", core.serialization.string()),
    groupId: core.serialization.property("group_id", core.serialization.number()),
});

export declare namespace DeleteGroupRequest {
    interface Raw {
        community_id: string;
        group_id: number;
    }
}
