/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as CommonApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const UpdateContestMetadataRequest: core.serialization.Schema<
    serializers.UpdateContestMetadataRequest.Raw,
    CommonApi.UpdateContestMetadataRequest
> = core.serialization.object({
    communityId: core.serialization.property("community_id", core.serialization.string()),
    contestAddress: core.serialization.property("contest_address", core.serialization.string()),
    name: core.serialization.string().optional(),
    imageUrl: core.serialization.property("image_url", core.serialization.string().optional()),
    topicId: core.serialization.property("topic_id", core.serialization.number().optional()),
});

export declare namespace UpdateContestMetadataRequest {
    interface Raw {
        community_id: string;
        contest_address: string;
        name?: string | null;
        image_url?: string | null;
        topic_id?: number | null;
    }
}
