/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../../index";

/**
 * @example
 *     {
 *         thread_id: 1
 *     }
 */
export interface GetCommentsRequest {
    limit?: string;
    /**
     * required for tRPC useInfiniteQuery hook, equivalent to page number
     */
    cursor?: string;
    order_by?: string;
    order_direction?: CommonApi.GetCommentsRequestOrderDirection;
    thread_id: number;
    comment_id?: number;
    include_user?: boolean;
    include_reactions?: boolean;
}
