/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         comment_id: 1,
 *         body: "body"
 *     }
 */
export interface UpdateCommentRequest {
    comment_id: number;
    body: string;
    canvas_signed_data?: string;
    canvas_msg_id?: string;
}
