/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CreateCommentResponseReactionAddressUserEmailNotificationInterval = "weekly" | "never";
export const CreateCommentResponseReactionAddressUserEmailNotificationInterval = {
    Weekly: "weekly",
    Never: "never",
} as const;
