/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CreateCommentResponseThreadReactionAddressUserEmailNotificationInterval = "weekly" | "never";
export const CreateCommentResponseThreadReactionAddressUserEmailNotificationInterval = {
    Weekly: "weekly",
    Never: "never",
} as const;
