/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CreateCommentResponseThreadAddressUserEmailNotificationInterval = "weekly" | "never";

export const CreateCommentResponseThreadAddressUserEmailNotificationInterval = {
    Weekly: "weekly",
    Never: "never",
} as const;
