/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface CreateCommentResponseThreadReactionAddress {
    id?: number;
    address: string;
    community_id: string;
    user_id?: number;
    verification_token?: string;
    verification_token_expires?: string;
    verified?: string;
    last_active?: string;
    ghost_address?: boolean;
    wallet_id?: CommonApi.CreateCommentResponseThreadReactionAddressWalletId;
    block_info?: string;
    role?: CommonApi.CreateCommentResponseThreadReactionAddressRole;
    is_banned?: boolean;
    hex?: string;
    oauth_provider?: string;
    oauth_email?: string;
    oauth_email_verified?: boolean;
    oauth_username?: string;
    oauth_phone_number?: string;
    User?: CommonApi.CreateCommentResponseThreadReactionAddressUser;
    created_at?: string;
    updated_at?: string;
}
