/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface CreateCommentResponse {
    id?: number;
    thread_id: number;
    address_id: number;
    body: string;
    parent_id?: number;
    content_url?: string;
    comment_level: number;
    canvas_signed_data?: string;
    canvas_msg_id?: string;
    created_by?: string;
    created_at?: string;
    updated_at?: string;
    deleted_at?: string;
    marked_as_spam_at?: string;
    user_tier_at_creation?: number;
    discord_meta?: CommonApi.CreateCommentResponseDiscordMeta;
    reply_count: number;
    reaction_count: number;
    reaction_weights_sum?: string;
    search?: CommonApi.CreateCommentResponseSearch;
    Address?: CommonApi.CreateCommentResponseAddress;
    Thread?: CommonApi.CreateCommentResponseThread;
    Reaction?: CommonApi.CreateCommentResponseReaction;
    CommentVersionHistories?: CommonApi.CreateCommentResponseCommentVersionHistoriesItem[];
    community_id: string;
}
