/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface CreateCommentRequestDiscordMeta {
    user: CommonApi.CreateCommentRequestDiscordMetaUser;
    channel_id: string;
    message_id: string;
}
