/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetCommentsResponseResultsItemReactionsItemAddressUser {
    id: number;
    email?: string;
    isAdmin?: boolean;
    disableRichText?: boolean;
    emailVerified?: boolean;
    selected_community_id?: string;
    emailNotificationInterval?: CommonApi.GetCommentsResponseResultsItemReactionsItemAddressUserEmailNotificationInterval;
    promotional_emails_enabled?: boolean;
    is_welcome_onboard_flow_complete?: boolean;
    profile: CommonApi.GetCommentsResponseResultsItemReactionsItemAddressUserProfile;
    xp_points?: number;
    created_at?: CommonApi.GetCommentsResponseResultsItemReactionsItemAddressUserCreatedAt;
    updated_at?: CommonApi.GetCommentsResponseResultsItemReactionsItemAddressUserUpdatedAt;
    ProfileTags?: CommonApi.GetCommentsResponseResultsItemReactionsItemAddressUserProfileTagsItem[];
}
