/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetCommentsResponseResultsItemReactionAddressUserProfileTagsItem {
    user_id: number;
    tag_id: number;
    created_at?: CommonApi.GetCommentsResponseResultsItemReactionAddressUserProfileTagsItemCreatedAt;
    updated_at?: CommonApi.GetCommentsResponseResultsItemReactionAddressUserProfileTagsItemUpdatedAt;
    Tag?: CommonApi.GetCommentsResponseResultsItemReactionAddressUserProfileTagsItemTag;
}
