/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetCommentsRequestOrderBy = "newest" | "oldest" | "mostLikes";
export const GetCommentsRequestOrderBy = {
    Newest: "newest",
    Oldest: "oldest",
    MostLikes: "mostLikes",
} as const;
