/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetCommentsResponseResultsItemReactionsItemAddress {
    id: number;
    address: string;
    community_id: string;
    user_id?: number;
    verification_token?: string;
    verification_token_expires?: CommonApi.GetCommentsResponseResultsItemReactionsItemAddressVerificationTokenExpires;
    verified?: CommonApi.GetCommentsResponseResultsItemReactionsItemAddressVerified;
    last_active?: CommonApi.GetCommentsResponseResultsItemReactionsItemAddressLastActive;
    ghost_address?: boolean;
    wallet_id?: CommonApi.GetCommentsResponseResultsItemReactionsItemAddressWalletId;
    block_info?: string;
    is_user_default?: boolean;
    role?: CommonApi.GetCommentsResponseResultsItemReactionsItemAddressRole;
    is_banned?: boolean;
    hex?: string;
    User?: CommonApi.GetCommentsResponseResultsItemReactionsItemAddressUser;
    created_at?: CommonApi.GetCommentsResponseResultsItemReactionsItemAddressCreatedAt;
    updated_at?: CommonApi.GetCommentsResponseResultsItemReactionsItemAddressUpdatedAt;
}
