/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetCommentsResponseResultsItemThreadReactionAddressUserEmailNotificationInterval = "weekly" | "never";
export const GetCommentsResponseResultsItemThreadReactionAddressUserEmailNotificationInterval = {
    Weekly: "weekly",
    Never: "never",
} as const;
