/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetCommentsResponseResultsItemCommentVersionHistoriesItem {
    id?: number;
    comment_id: number;
    text: string;
    timestamp: string;
    content_url?: string;
}
