/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetCommentsResponseResultsItemAddressUserProfileTagsItem {
    user_id: number;
    tag_id: number;
    created_at?: CommonApi.GetCommentsResponseResultsItemAddressUserProfileTagsItemCreatedAt;
    updated_at?: CommonApi.GetCommentsResponseResultsItemAddressUserProfileTagsItemUpdatedAt;
}
