/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetCommentsResponseResultsItemThreadAddressUserEmailNotificationInterval = "weekly" | "never";
export const GetCommentsResponseResultsItemThreadAddressUserEmailNotificationInterval = {
    Weekly: "weekly",
    Never: "never",
} as const;
