/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetCommentsResponseResultsItemReactionAddressUserEmailNotificationInterval = "weekly" | "never";
export const GetCommentsResponseResultsItemReactionAddressUserEmailNotificationInterval = {
    Weekly: "weekly",
    Never: "never",
} as const;
