/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetCommentsResponseResultsItemThreadDiscordMeta {
    user: CommonApi.GetCommentsResponseResultsItemThreadDiscordMetaUser;
    channel_id: string;
    message_id: string;
}
