/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetCommentsResponseResultsItemAddressRole = "admin" | "moderator" | "member";
export const GetCommentsResponseResultsItemAddressRole = {
    Admin: "admin",
    Moderator: "moderator",
    Member: "member",
} as const;
