/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ToggleCommentSpamResponseReactionAddressWalletId =
    | "magic"
    | "polkadot"
    | "metamask"
    | "walletconnect"
    | "keplr-ethereum"
    | "keplr"
    | "leap"
    | "near"
    | "terrastation"
    | "terra-walletconnect"
    | "cosm-metamask"
    | "phantom"
    | "coinbase";
export const ToggleCommentSpamResponseReactionAddressWalletId = {
    Magic: "magic",
    Polkadot: "polkadot",
    Metamask: "metamask",
    Walletconnect: "walletconnect",
    KeplrEthereum: "keplr-ethereum",
    Keplr: "keplr",
    Leap: "leap",
    Near: "near",
    Terrastation: "terrastation",
    TerraWalletconnect: "terra-walletconnect",
    CosmMetamask: "cosm-metamask",
    Phantom: "phantom",
    Coinbase: "coinbase",
} as const;
