/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ToggleCommentSpamResponseThreadReactionAddressUserEmailNotificationInterval = "weekly" | "never";
export const ToggleCommentSpamResponseThreadReactionAddressUserEmailNotificationInterval = {
    Weekly: "weekly",
    Never: "never",
} as const;
