/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ToggleCommentSpamResponseThreadReactionAddressUserApiKey {
    user_id?: number;
    hashed_api_key: string;
    salt: string;
    created_at?: string;
    updated_at?: string;
}
