/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ToggleCommentSpamResponseThreadReactionsItemAddressUserEmailNotificationInterval = "weekly" | "never";
export const ToggleCommentSpamResponseThreadReactionsItemAddressUserEmailNotificationInterval = {
    Weekly: "weekly",
    Never: "never",
} as const;
