/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UpdateCommentResponseThreadAddressUserEmailNotificationInterval = "weekly" | "never";

export const UpdateCommentResponseThreadAddressUserEmailNotificationInterval = {
    Weekly: "weekly",
    Never: "never",
} as const;
