/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const CreateCommentResponseThreadLinksItemSource: core.serialization.Schema<
    serializers.CreateCommentResponseThreadLinksItemSource.Raw,
    CommonApi.CreateCommentResponseThreadLinksItemSource
> = core.serialization.enum_(["snapshot", "proposal", "thread", "web", "template"]);

export declare namespace CreateCommentResponseThreadLinksItemSource {
    type Raw = "snapshot" | "proposal" | "thread" | "web" | "template";
}
