/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { CreateCommentResponseAddressUserProfileTagsItemTag } from "./CreateCommentResponseAddressUserProfileTagsItemTag";

export const CreateCommentResponseAddressUserProfileTagsItem: core.serialization.ObjectSchema<
    serializers.CreateCommentResponseAddressUserProfileTagsItem.Raw,
    CommonApi.CreateCommentResponseAddressUserProfileTagsItem
> = core.serialization.object({
    userId: core.serialization.property("user_id", core.serialization.number()),
    tagId: core.serialization.property("tag_id", core.serialization.number()),
    createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date().optional()),
    tag: core.serialization.property("Tag", CreateCommentResponseAddressUserProfileTagsItemTag.optional()),
});

export declare namespace CreateCommentResponseAddressUserProfileTagsItem {
    interface Raw {
        user_id: number;
        tag_id: number;
        created_at?: string | null;
        updated_at?: string | null;
        Tag?: CreateCommentResponseAddressUserProfileTagsItemTag.Raw | null;
    }
}
