/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const CreateCommentResponseThreadTopicWeightedVoting: core.serialization.Schema<
    serializers.CreateCommentResponseThreadTopicWeightedVoting.Raw,
    CommonApi.CreateCommentResponseThreadTopicWeightedVoting
> = core.serialization.enum_(["stake", "erc20"]);

export declare namespace CreateCommentResponseThreadTopicWeightedVoting {
    type Raw = "stake" | "erc20";
}
