/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const CreateCommentResponseThreadCollaboratorsItemRole: core.serialization.Schema<
    serializers.CreateCommentResponseThreadCollaboratorsItemRole.Raw,
    CommonApi.CreateCommentResponseThreadCollaboratorsItemRole
> = core.serialization.enum_(["admin", "moderator", "member"]);

export declare namespace CreateCommentResponseThreadCollaboratorsItemRole {
    type Raw = "admin" | "moderator" | "member";
}
