/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { CreateCommentResponseThreadDiscordMetaUser } from "./CreateCommentResponseThreadDiscordMetaUser";

export const CreateCommentResponseThreadDiscordMeta: core.serialization.ObjectSchema<
    serializers.CreateCommentResponseThreadDiscordMeta.Raw,
    CommonApi.CreateCommentResponseThreadDiscordMeta
> = core.serialization.object({
    user: CreateCommentResponseThreadDiscordMetaUser,
    channelId: core.serialization.property("channel_id", core.serialization.string()),
    messageId: core.serialization.property("message_id", core.serialization.string()),
});

export declare namespace CreateCommentResponseThreadDiscordMeta {
    interface Raw {
        user: CreateCommentResponseThreadDiscordMetaUser.Raw;
        channel_id: string;
        message_id: string;
    }
}
