/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { CreateCommentResponseThreadLinksItemSource } from "./CreateCommentResponseThreadLinksItemSource";

export const CreateCommentResponseThreadLinksItem: core.serialization.ObjectSchema<
    serializers.CreateCommentResponseThreadLinksItem.Raw,
    CommonApi.CreateCommentResponseThreadLinksItem
> = core.serialization.object({
    source: CreateCommentResponseThreadLinksItemSource,
    identifier: core.serialization.string(),
    title: core.serialization.string().optional(),
});

export declare namespace CreateCommentResponseThreadLinksItem {
    interface Raw {
        source: CreateCommentResponseThreadLinksItemSource.Raw;
        identifier: string;
        title?: string | null;
    }
}
