/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const CreateCommentResponseAddressRole: core.serialization.Schema<
    serializers.CreateCommentResponseAddressRole.Raw,
    CommonApi.CreateCommentResponseAddressRole
> = core.serialization.enum_(["admin", "moderator", "member"]);

export declare namespace CreateCommentResponseAddressRole {
    type Raw = "admin" | "moderator" | "member";
}
