/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetCommentsResponseResultsItemReactionAddressRole: core.serialization.Schema<
    serializers.GetCommentsResponseResultsItemReactionAddressRole.Raw,
    CommonApi.GetCommentsResponseResultsItemReactionAddressRole
> = core.serialization.enum_(["admin", "moderator", "member"]);

export declare namespace GetCommentsResponseResultsItemReactionAddressRole {
    type Raw = "admin" | "moderator" | "member";
}
