/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetCommentsResponseResultsItemThreadReactionAddressRole: core.serialization.Schema<
    serializers.GetCommentsResponseResultsItemThreadReactionAddressRole.Raw,
    CommonApi.GetCommentsResponseResultsItemThreadReactionAddressRole
> = core.serialization.enum_(["admin", "moderator", "member"]);

export declare namespace GetCommentsResponseResultsItemThreadReactionAddressRole {
    type Raw = "admin" | "moderator" | "member";
}
