/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetCommentsResponseResultsItemThreadAddressRole: core.serialization.Schema<
    serializers.GetCommentsResponseResultsItemThreadAddressRole.Raw,
    CommonApi.GetCommentsResponseResultsItemThreadAddressRole
> = core.serialization.enum_(["admin", "moderator", "member"]);

export declare namespace GetCommentsResponseResultsItemThreadAddressRole {
    type Raw = "admin" | "moderator" | "member";
}
