/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetCommentsResponseResultsItemReactionAddressUserEmailNotificationInterval: core.serialization.Schema<
    serializers.GetCommentsResponseResultsItemReactionAddressUserEmailNotificationInterval.Raw,
    CommonApi.GetCommentsResponseResultsItemReactionAddressUserEmailNotificationInterval
> = core.serialization.enum_(["weekly", "never"]);

export declare namespace GetCommentsResponseResultsItemReactionAddressUserEmailNotificationInterval {
    type Raw = "weekly" | "never";
}
