/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetCommentsResponseResultsItemThreadAddressUserEmailNotificationInterval: core.serialization.Schema<
    serializers.GetCommentsResponseResultsItemThreadAddressUserEmailNotificationInterval.Raw,
    CommonApi.GetCommentsResponseResultsItemThreadAddressUserEmailNotificationInterval
> = core.serialization.enum_(["weekly", "never"]);

export declare namespace GetCommentsResponseResultsItemThreadAddressUserEmailNotificationInterval {
    type Raw = "weekly" | "never";
}
