/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const UpdateCommentResponseThreadThreadVersionHistoriesItem: core.serialization.ObjectSchema<
    serializers.UpdateCommentResponseThreadThreadVersionHistoriesItem.Raw,
    CommonApi.UpdateCommentResponseThreadThreadVersionHistoriesItem
> = core.serialization.object({
    id: core.serialization.number().optional(),
    threadId: core.serialization.property("thread_id", core.serialization.number()),
    address: core.serialization.string(),
    body: core.serialization.string(),
    timestamp: core.serialization.date(),
    contentUrl: core.serialization.property("content_url", core.serialization.string().optional()),
});

export declare namespace UpdateCommentResponseThreadThreadVersionHistoriesItem {
    interface Raw {
        id?: number | null;
        thread_id: number;
        address: string;
        body: string;
        timestamp: string;
        content_url?: string | null;
    }
}
