/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const UpdateCommentResponseReactionAddressRole: core.serialization.Schema<
    serializers.UpdateCommentResponseReactionAddressRole.Raw,
    CommonApi.UpdateCommentResponseReactionAddressRole
> = core.serialization.enum_(["admin", "moderator", "member"]);

export declare namespace UpdateCommentResponseReactionAddressRole {
    type Raw = "admin" | "moderator" | "member";
}
