/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const UpdateCommentResponseThreadReactionAddressRole: core.serialization.Schema<
    serializers.UpdateCommentResponseThreadReactionAddressRole.Raw,
    CommonApi.UpdateCommentResponseThreadReactionAddressRole
> = core.serialization.enum_(["admin", "moderator", "member"]);

export declare namespace UpdateCommentResponseThreadReactionAddressRole {
    type Raw = "admin" | "moderator" | "member";
}
