/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { UpdateCommentResponseThreadLinksItemSource } from "./UpdateCommentResponseThreadLinksItemSource";

export const UpdateCommentResponseThreadLinksItem: core.serialization.ObjectSchema<
    serializers.UpdateCommentResponseThreadLinksItem.Raw,
    CommonApi.UpdateCommentResponseThreadLinksItem
> = core.serialization.object({
    source: UpdateCommentResponseThreadLinksItemSource,
    identifier: core.serialization.string(),
    title: core.serialization.string().optional(),
});

export declare namespace UpdateCommentResponseThreadLinksItem {
    interface Raw {
        source: UpdateCommentResponseThreadLinksItemSource.Raw;
        identifier: string;
        title?: string | null;
    }
}
