/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";
import { UpdateCommentResponseThreadReactionAddressWalletId } from "./UpdateCommentResponseThreadReactionAddressWalletId";
import { UpdateCommentResponseThreadReactionAddressRole } from "./UpdateCommentResponseThreadReactionAddressRole";
import { UpdateCommentResponseThreadReactionAddressUser } from "./UpdateCommentResponseThreadReactionAddressUser";

export const UpdateCommentResponseThreadReactionAddress: core.serialization.ObjectSchema<
    serializers.UpdateCommentResponseThreadReactionAddress.Raw,
    CommonApi.UpdateCommentResponseThreadReactionAddress
> = core.serialization.object({
    id: core.serialization.number().optional(),
    address: core.serialization.string(),
    communityId: core.serialization.property("community_id", core.serialization.string()),
    userId: core.serialization.property("user_id", core.serialization.number().optional()),
    verificationToken: core.serialization.property("verification_token", core.serialization.string().optional()),
    verificationTokenExpires: core.serialization.property(
        "verification_token_expires",
        core.serialization.date().optional()
    ),
    verified: core.serialization.date().optional(),
    lastActive: core.serialization.property("last_active", core.serialization.date().optional()),
    ghostAddress: core.serialization.property("ghost_address", core.serialization.boolean().optional()),
    walletId: core.serialization.property("wallet_id", UpdateCommentResponseThreadReactionAddressWalletId.optional()),
    blockInfo: core.serialization.property("block_info", core.serialization.string().optional()),
    isUserDefault: core.serialization.property("is_user_default", core.serialization.boolean().optional()),
    role: UpdateCommentResponseThreadReactionAddressRole.optional(),
    isBanned: core.serialization.property("is_banned", core.serialization.boolean().optional()),
    hex: core.serialization.string().optional(),
    user: core.serialization.property("User", UpdateCommentResponseThreadReactionAddressUser.optional()),
    createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
    updatedAt: core.serialization.property("updated_at", core.serialization.date().optional()),
});

export declare namespace UpdateCommentResponseThreadReactionAddress {
    interface Raw {
        id?: number | null;
        address: string;
        community_id: string;
        user_id?: number | null;
        verification_token?: string | null;
        verification_token_expires?: string | null;
        verified?: string | null;
        last_active?: string | null;
        ghost_address?: boolean | null;
        wallet_id?: UpdateCommentResponseThreadReactionAddressWalletId.Raw | null;
        block_info?: string | null;
        is_user_default?: boolean | null;
        role?: UpdateCommentResponseThreadReactionAddressRole.Raw | null;
        is_banned?: boolean | null;
        hex?: string | null;
        User?: UpdateCommentResponseThreadReactionAddressUser.Raw | null;
        created_at?: string | null;
        updated_at?: string | null;
    }
}
