/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CommonApi from "../../../../api/index";
import * as core from "../../../../core";

export const UpdateCommentResponseReactionAddressUserEmailNotificationInterval: core.serialization.Schema<
    serializers.UpdateCommentResponseReactionAddressUserEmailNotificationInterval.Raw,
    CommonApi.UpdateCommentResponseReactionAddressUserEmailNotificationInterval
> = core.serialization.enum_(["weekly", "never"]);

export declare namespace UpdateCommentResponseReactionAddressUserEmailNotificationInterval {
    type Raw = "weekly" | "never";
}
