/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetGlobalActivityResponseResultsItemCommentsItem {
    id: number;
    thread_id: number;
    address_id: number;
    body: string;
    parent_id?: number;
    content_url?: string;
    comment_level: number;
    canvas_signed_data?: string;
    canvas_msg_id?: string;
    created_by?: string;
    created_at?: CommonApi.GetGlobalActivityResponseResultsItemCommentsItemCreatedAt;
    updated_at?: CommonApi.GetGlobalActivityResponseResultsItemCommentsItemUpdatedAt;
    deleted_at?: CommonApi.GetGlobalActivityResponseResultsItemCommentsItemDeletedAt;
    marked_as_spam_at?: CommonApi.GetGlobalActivityResponseResultsItemCommentsItemMarkedAsSpamAt;
    user_tier_at_creation?: number;
    discord_meta?: CommonApi.GetGlobalActivityResponseResultsItemCommentsItemDiscordMeta;
    reply_count: number;
    reaction_count: number;
    reaction_weights_sum?: string;
    search?: unknown;
    Address?: CommonApi.GetGlobalActivityResponseResultsItemCommentsItemAddress;
    Thread?: unknown;
    Reaction?: CommonApi.GetGlobalActivityResponseResultsItemCommentsItemReaction;
    CommentVersionHistories?: CommonApi.GetGlobalActivityResponseResultsItemCommentsItemCommentVersionHistoriesItem[];
    community_id: string;
    last_active?: CommonApi.GetGlobalActivityResponseResultsItemCommentsItemLastActive;
    address: string;
    profile_name?: string;
    avatar_url?: string;
    user_id: number;
}
