/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetGlobalActivityResponseResultsItemCommentsItemAddressUserProfileTagsItem {
    user_id: number;
    tag_id: number;
    created_at?: CommonApi.GetGlobalActivityResponseResultsItemCommentsItemAddressUserProfileTagsItemCreatedAt;
    updated_at?: CommonApi.GetGlobalActivityResponseResultsItemCommentsItemAddressUserProfileTagsItemUpdatedAt;
}
