/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetGlobalActivityResponseResultsItemReactionAddressUser {
    id: number;
    email?: string;
    isAdmin?: boolean;
    disableRichText?: boolean;
    emailVerified?: boolean;
    selected_community_id?: string;
    emailNotificationInterval?: CommonApi.GetGlobalActivityResponseResultsItemReactionAddressUserEmailNotificationInterval;
    promotional_emails_enabled?: boolean;
    is_welcome_onboard_flow_complete?: boolean;
    profile: CommonApi.GetGlobalActivityResponseResultsItemReactionAddressUserProfile;
    xp_points?: number;
    created_at?: CommonApi.GetGlobalActivityResponseResultsItemReactionAddressUserCreatedAt;
    updated_at?: CommonApi.GetGlobalActivityResponseResultsItemReactionAddressUserUpdatedAt;
    ProfileTags?: CommonApi.GetGlobalActivityResponseResultsItemReactionAddressUserProfileTagsItem[];
    unsubscribe_uuid?: string;
    tier?: number;
    referred_by_address?: string;
    xp_referrer_points?: number;
}
