/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetGlobalActivityRequestOrderDirection = "ASC" | "DESC";

export const GetGlobalActivityRequestOrderDirection = {
    Asc: "ASC",
    Desc: "DESC",
} as const;
