/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetGlobalActivityResponseResultsItemContestActionsItemContest {
    /** On-Chain Contest Manager */
    ContestManager: CommonApi.GetGlobalActivityResponseResultsItemContestActionsItemContestContestManager;
    contest_id: number;
    contest_address: string;
    start_time: CommonApi.GetGlobalActivityResponseResultsItemContestActionsItemContestStartTime;
    end_time: CommonApi.GetGlobalActivityResponseResultsItemContestActionsItemContestEndTime;
    score?: CommonApi.GetGlobalActivityResponseResultsItemContestActionsItemContestScoreItem[];
    contest_name?: string;
    contest_interval?: number;
    content_id?: number;
    contest_cancelled?: boolean;
    thread_id?: number;
}
