/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetGlobalActivityResponseResultsItemAssociatedContestsItemScoreItem {
    prize: string;
    votes: string;
    content_id: string;
    creator_address: string;
}
