/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetGlobalActivityResponseResultsItemReactionsItemAddress {
    id: number;
    address: string;
    community_id: string;
    user_id?: number;
    verification_token?: string;
    verification_token_expires?: CommonApi.GetGlobalActivityResponseResultsItemReactionsItemAddressVerificationTokenExpires;
    verified?: CommonApi.GetGlobalActivityResponseResultsItemReactionsItemAddressVerified;
    last_active?: CommonApi.GetGlobalActivityResponseResultsItemReactionsItemAddressLastActive;
    ghost_address?: boolean;
    wallet_id?: CommonApi.GetGlobalActivityResponseResultsItemReactionsItemAddressWalletId;
    block_info?: string;
    role?: CommonApi.GetGlobalActivityResponseResultsItemReactionsItemAddressRole;
    is_banned?: boolean;
    hex?: string;
    User?: CommonApi.GetGlobalActivityResponseResultsItemReactionsItemAddressUser;
    created_at?: CommonApi.GetGlobalActivityResponseResultsItemReactionsItemAddressCreatedAt;
    updated_at?: CommonApi.GetGlobalActivityResponseResultsItemReactionsItemAddressUpdatedAt;
}
