/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetGlobalActivityResponseResultsItemDiscordMeta {
    user: CommonApi.GetGlobalActivityResponseResultsItemDiscordMetaUser;
    channel_id: string;
    message_id: string;
}
