/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetGlobalActivityResponseItemRecentCommentsItem {
    id: number;
    address: string;
    user_id?: number;
    profile_name?: string;
    profile_avatar?: string;
    text: string;
    content_url?: string;
    created_at: string;
    updated_at?: string;
    deleted_at?: string;
    marked_as_spam_at?: string;
    discord_meta?: CommonApi.GetGlobalActivityResponseItemRecentCommentsItemDiscordMeta;
}
