/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetGlobalActivityResponseResultsItemCollaboratorsItemUserProfileTagsItem {
    user_id: number;
    tag_id: number;
    created_at?: CommonApi.GetGlobalActivityResponseResultsItemCollaboratorsItemUserProfileTagsItemCreatedAt;
    updated_at?: CommonApi.GetGlobalActivityResponseResultsItemCollaboratorsItemUserProfileTagsItemUpdatedAt;
}
