/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetGlobalActivityResponseResultsItemCommentsItemReactionAddress {
    id: number;
    address: string;
    community_id: string;
    user_id?: number;
    verification_token?: string;
    verification_token_expires?: CommonApi.GetGlobalActivityResponseResultsItemCommentsItemReactionAddressVerificationTokenExpires;
    verified?: CommonApi.GetGlobalActivityResponseResultsItemCommentsItemReactionAddressVerified;
    last_active?: CommonApi.GetGlobalActivityResponseResultsItemCommentsItemReactionAddressLastActive;
    ghost_address?: boolean;
    wallet_id?: CommonApi.GetGlobalActivityResponseResultsItemCommentsItemReactionAddressWalletId;
    block_info?: string;
    role?: CommonApi.GetGlobalActivityResponseResultsItemCommentsItemReactionAddressRole;
    is_banned?: boolean;
    hex?: string;
    User?: CommonApi.GetGlobalActivityResponseResultsItemCommentsItemReactionAddressUser;
    created_at?: CommonApi.GetGlobalActivityResponseResultsItemCommentsItemReactionAddressCreatedAt;
    updated_at?: CommonApi.GetGlobalActivityResponseResultsItemCommentsItemReactionAddressUpdatedAt;
}
