/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetGlobalActivityResponseResultsItemReactionAddressWalletId =
    | "magic"
    | "privy"
    | "polkadot"
    | "metamask"
    | "walletconnect"
    | "keplr-ethereum"
    | "keplr"
    | "leap"
    | "near"
    | "terrastation"
    | "terra-walletconnect"
    | "cosm-metamask"
    | "phantom"
    | "backpack"
    | "solflare"
    | "coinbase"
    | "farcaster"
    | "okx"
    | "sui-wallet";
export const GetGlobalActivityResponseResultsItemReactionAddressWalletId = {
    Magic: "magic",
    Privy: "privy",
    Polkadot: "polkadot",
    Metamask: "metamask",
    Walletconnect: "walletconnect",
    KeplrEthereum: "keplr-ethereum",
    Keplr: "keplr",
    Leap: "leap",
    Near: "near",
    Terrastation: "terrastation",
    TerraWalletconnect: "terra-walletconnect",
    CosmMetamask: "cosm-metamask",
    Phantom: "phantom",
    Backpack: "backpack",
    Solflare: "solflare",
    Coinbase: "coinbase",
    Farcaster: "farcaster",
    Okx: "okx",
    SuiWallet: "sui-wallet",
} as const;
