/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetGlobalActivityResponseResultsItemReactionAddress {
    id: number;
    address: string;
    community_id: string;
    user_id?: number;
    verification_token?: string;
    verification_token_expires?: CommonApi.GetGlobalActivityResponseResultsItemReactionAddressVerificationTokenExpires;
    verified?: CommonApi.GetGlobalActivityResponseResultsItemReactionAddressVerified;
    last_active?: CommonApi.GetGlobalActivityResponseResultsItemReactionAddressLastActive;
    ghost_address?: boolean;
    wallet_id?: CommonApi.GetGlobalActivityResponseResultsItemReactionAddressWalletId;
    block_info?: string;
    role?: CommonApi.GetGlobalActivityResponseResultsItemReactionAddressRole;
    is_banned?: boolean;
    hex?: string;
    User?: CommonApi.GetGlobalActivityResponseResultsItemReactionAddressUser;
    created_at?: CommonApi.GetGlobalActivityResponseResultsItemReactionAddressCreatedAt;
    updated_at?: CommonApi.GetGlobalActivityResponseResultsItemReactionAddressUpdatedAt;
}
