/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetGlobalActivityResponseResultsItemAssociatedContestsItem {
    /** On-Chain Contest Manager */
    ContestManager: CommonApi.GetGlobalActivityResponseResultsItemAssociatedContestsItemContestManager;
    contest_id: number;
    contest_address: string;
    start_time: CommonApi.GetGlobalActivityResponseResultsItemAssociatedContestsItemStartTime;
    end_time: CommonApi.GetGlobalActivityResponseResultsItemAssociatedContestsItemEndTime;
    score?: CommonApi.GetGlobalActivityResponseResultsItemAssociatedContestsItemScoreItem[];
    contest_name?: string;
    contest_interval?: number;
    content_id?: number;
    contest_cancelled?: boolean;
    thread_id?: number;
}
