/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetUserActivityResponseResultsItemTopic {
    id?: number;
    name?: string;
    community_id: string;
    description?: string;
    telegram?: string;
    featured_in_sidebar?: boolean;
    featured_in_new_post?: boolean;
    default_offchain_template?: string;
    order?: number;
    channel_id?: string;
    default_offchain_template_backup?: string;
    weighted_voting?: CommonApi.GetUserActivityResponseResultsItemTopicWeightedVoting;
    chain_node_id?: number;
    /** token address, used for ERC20/SPL/SuiToken topics (for SuiToken, this stores the coin type) */
    token_address?: string;
    token_symbol?: string;
    /** vote weight multiplier, used for token weighted topics */
    vote_weight_multiplier?: number;
    /** number of decimals of token */
    token_decimals?: number;
    allow_tokenized_threads?: boolean;
    created_at?: CommonApi.GetUserActivityResponseResultsItemTopicCreatedAt;
    updated_at?: CommonApi.GetUserActivityResponseResultsItemTopicUpdatedAt;
    deleted_at?: CommonApi.GetUserActivityResponseResultsItemTopicDeletedAt;
    archived_at?: CommonApi.GetUserActivityResponseResultsItemTopicArchivedAt;
    contest_topics?: unknown;
    total_threads?: number;
    active_contest_managers?: CommonApi.GetUserActivityResponseResultsItemTopicActiveContestManagersItem[];
    chain_node_url?: string;
    eth_chain_id?: number;
}
