/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetUserActivityResponseResultsItemCommentsItemAddress {
    id: number;
    address: string;
    community_id: string;
    user_id?: number;
    verification_token?: string;
    verification_token_expires?: CommonApi.GetUserActivityResponseResultsItemCommentsItemAddressVerificationTokenExpires;
    verified?: CommonApi.GetUserActivityResponseResultsItemCommentsItemAddressVerified;
    last_active?: CommonApi.GetUserActivityResponseResultsItemCommentsItemAddressLastActive;
    ghost_address?: boolean;
    wallet_id?: CommonApi.GetUserActivityResponseResultsItemCommentsItemAddressWalletId;
    block_info?: string;
    role?: CommonApi.GetUserActivityResponseResultsItemCommentsItemAddressRole;
    is_banned?: boolean;
    hex?: string;
    User?: CommonApi.GetUserActivityResponseResultsItemCommentsItemAddressUser;
    created_at?: CommonApi.GetUserActivityResponseResultsItemCommentsItemAddressCreatedAt;
    updated_at?: CommonApi.GetUserActivityResponseResultsItemCommentsItemAddressUpdatedAt;
}
