/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetUserActivityResponseResultsItemReactionAddress {
    id: number;
    address: string;
    community_id: string;
    user_id?: number;
    verification_token?: string;
    verification_token_expires?: CommonApi.GetUserActivityResponseResultsItemReactionAddressVerificationTokenExpires;
    verified?: CommonApi.GetUserActivityResponseResultsItemReactionAddressVerified;
    last_active?: CommonApi.GetUserActivityResponseResultsItemReactionAddressLastActive;
    ghost_address?: boolean;
    wallet_id?: CommonApi.GetUserActivityResponseResultsItemReactionAddressWalletId;
    block_info?: string;
    role?: CommonApi.GetUserActivityResponseResultsItemReactionAddressRole;
    is_banned?: boolean;
    hex?: string;
    User?: CommonApi.GetUserActivityResponseResultsItemReactionAddressUser;
    created_at?: CommonApi.GetUserActivityResponseResultsItemReactionAddressCreatedAt;
    updated_at?: CommonApi.GetUserActivityResponseResultsItemReactionAddressUpdatedAt;
}
