/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetUserActivityResponseResultsItemReactionAddressUserEmailNotificationInterval = "weekly" | "never";
export const GetUserActivityResponseResultsItemReactionAddressUserEmailNotificationInterval = {
    Weekly: "weekly",
    Never: "never",
} as const;
