/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetUserActivityResponseResultsItemCollaboratorsItemUserProfileTagsItem {
    user_id: number;
    tag_id: number;
    created_at?: CommonApi.GetUserActivityResponseResultsItemCollaboratorsItemUserProfileTagsItemCreatedAt;
    updated_at?: CommonApi.GetUserActivityResponseResultsItemCollaboratorsItemUserProfileTagsItemUpdatedAt;
}
