/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetUserActivityResponseResultsItemCommentsItem {
    id: number;
    thread_id: number;
    address_id: number;
    body: string;
    parent_id?: number;
    content_url?: string;
    comment_level: number;
    canvas_signed_data?: string;
    canvas_msg_id?: string;
    created_by?: string;
    created_at?: CommonApi.GetUserActivityResponseResultsItemCommentsItemCreatedAt;
    updated_at?: CommonApi.GetUserActivityResponseResultsItemCommentsItemUpdatedAt;
    deleted_at?: CommonApi.GetUserActivityResponseResultsItemCommentsItemDeletedAt;
    marked_as_spam_at?: CommonApi.GetUserActivityResponseResultsItemCommentsItemMarkedAsSpamAt;
    user_tier_at_creation?: number;
    discord_meta?: CommonApi.GetUserActivityResponseResultsItemCommentsItemDiscordMeta;
    reply_count: number;
    reaction_count: number;
    reaction_weights_sum?: string;
    search?: unknown;
    Address?: CommonApi.GetUserActivityResponseResultsItemCommentsItemAddress;
    Thread?: unknown;
    Reaction?: CommonApi.GetUserActivityResponseResultsItemCommentsItemReaction;
    CommentVersionHistories?: CommonApi.GetUserActivityResponseResultsItemCommentsItemCommentVersionHistoriesItem[];
    community_id: string;
    last_active?: CommonApi.GetUserActivityResponseResultsItemCommentsItemLastActive;
    address: string;
    profile_name?: string;
    avatar_url?: string;
    user_id: number;
}
