/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetUserActivityResponseResultsItem {
    id: number;
    address_id: number;
    title: string;
    kind: string;
    stage?: string;
    body: string;
    url?: string;
    topic_id?: number;
    pinned?: boolean;
    community_id: string;
    view_count?: number;
    links?: CommonApi.GetUserActivityResponseResultsItemLinksItem[];
    content_url?: string;
    read_only?: boolean;
    has_poll?: boolean;
    canvas_signed_data?: string;
    canvas_msg_id?: string;
    created_at?: CommonApi.GetUserActivityResponseResultsItemCreatedAt;
    updated_at?: CommonApi.GetUserActivityResponseResultsItemUpdatedAt;
    last_edited?: CommonApi.GetUserActivityResponseResultsItemLastEdited;
    deleted_at?: CommonApi.GetUserActivityResponseResultsItemDeletedAt;
    last_commented_on?: CommonApi.GetUserActivityResponseResultsItemLastCommentedOn;
    marked_as_spam_at?: CommonApi.GetUserActivityResponseResultsItemMarkedAsSpamAt;
    archived_at?: CommonApi.GetUserActivityResponseResultsItemArchivedAt;
    locked_at?: CommonApi.GetUserActivityResponseResultsItemLockedAt;
    discord_meta?: CommonApi.GetUserActivityResponseResultsItemDiscordMeta;
    user_tier_at_creation?: number;
    reaction_count?: number;
    reaction_weights_sum?: string;
    comment_count?: number;
    activity_rank_date?: CommonApi.GetUserActivityResponseResultsItemActivityRankDate;
    created_by?: string;
    profile_name?: string;
    search?: CommonApi.GetUserActivityResponseResultsItemSearch;
    is_linking_token?: boolean;
    launchpad_token_address?: string;
    Address?: CommonApi.GetUserActivityResponseResultsItemAddress;
    Reaction?: CommonApi.GetUserActivityResponseResultsItemReaction;
    topic?: CommonApi.GetUserActivityResponseResultsItemTopic;
    collaborators?: CommonApi.GetUserActivityResponseResultsItemCollaboratorsItem[];
    reactions?: CommonApi.GetUserActivityResponseResultsItemReactionsItem[];
    ThreadVersionHistories?: CommonApi.GetUserActivityResponseResultsItemThreadVersionHistoriesItem[];
    associatedContests?: CommonApi.GetUserActivityResponseResultsItemAssociatedContestsItem[];
    ContestActions?: CommonApi.GetUserActivityResponseResultsItemContestActionsItem[];
    Comments?: CommonApi.GetUserActivityResponseResultsItemCommentsItem[];
    /** total number of thread results for the query */
    total_num_thread_results?: number;
    user_id?: number;
    user_tier?: number;
    avatar_url?: string;
    address_last_active?: CommonApi.GetUserActivityResponseResultsItemAddressLastActive;
}
