/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetUserActivityResponseResultsItemAssociatedContestsItem {
    /** On-Chain Contest Manager */
    ContestManager: CommonApi.GetUserActivityResponseResultsItemAssociatedContestsItemContestManager;
    contest_id: number;
    contest_address: string;
    start_time: CommonApi.GetUserActivityResponseResultsItemAssociatedContestsItemStartTime;
    end_time: CommonApi.GetUserActivityResponseResultsItemAssociatedContestsItemEndTime;
    score?: CommonApi.GetUserActivityResponseResultsItemAssociatedContestsItemScoreItem[];
    contest_name?: string;
    contest_interval?: number;
    content_id?: number;
    contest_cancelled?: boolean;
    thread_id?: number;
}
