/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetUserActivityResponseResultsItemCommentsItemCommentVersionHistoriesItem {
    id: number;
    comment_id: number;
    body: string;
    timestamp: CommonApi.GetUserActivityResponseResultsItemCommentsItemCommentVersionHistoriesItemTimestamp;
    content_url?: string;
}
