/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetUserActivityResponseResultsItemRecentCommentsItemDiscordMeta {
    user: CommonApi.GetUserActivityResponseResultsItemRecentCommentsItemDiscordMetaUser;
    channel_id: string;
    message_id: string;
}
