/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetUserActivityResponseResultsItemCommentsItemReactionAddressUserEmailNotificationInterval =
    | "weekly"
    | "never";
export const GetUserActivityResponseResultsItemCommentsItemReactionAddressUserEmailNotificationInterval = {
    Weekly: "weekly",
    Never: "never",
} as const;
