/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetUserActivityResponseResultsItemReactionsItemAddressUserProfileTagsItem {
    user_id: number;
    tag_id: number;
    created_at?: CommonApi.GetUserActivityResponseResultsItemReactionsItemAddressUserProfileTagsItemCreatedAt;
    updated_at?: CommonApi.GetUserActivityResponseResultsItemReactionsItemAddressUserProfileTagsItemUpdatedAt;
}
