/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetUserActivityResponseResultsItemCommentsItemReactionAddress {
    id: number;
    address: string;
    community_id: string;
    user_id?: number;
    verification_token?: string;
    verification_token_expires?: CommonApi.GetUserActivityResponseResultsItemCommentsItemReactionAddressVerificationTokenExpires;
    verified?: CommonApi.GetUserActivityResponseResultsItemCommentsItemReactionAddressVerified;
    last_active?: CommonApi.GetUserActivityResponseResultsItemCommentsItemReactionAddressLastActive;
    ghost_address?: boolean;
    wallet_id?: CommonApi.GetUserActivityResponseResultsItemCommentsItemReactionAddressWalletId;
    block_info?: string;
    role?: CommonApi.GetUserActivityResponseResultsItemCommentsItemReactionAddressRole;
    is_banned?: boolean;
    hex?: string;
    User?: CommonApi.GetUserActivityResponseResultsItemCommentsItemReactionAddressUser;
    created_at?: CommonApi.GetUserActivityResponseResultsItemCommentsItemReactionAddressCreatedAt;
    updated_at?: CommonApi.GetUserActivityResponseResultsItemCommentsItemReactionAddressUpdatedAt;
}
