/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetTokensRequestOrderBy = "name" | "price" | "market_cap";
export const GetTokensRequestOrderBy = {
    Name: "name",
    Price: "price",
    MarketCap: "market_cap",
} as const;
