/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface CancelContestMetadataResponse {
    contest_managers: CommonApi.CancelContestMetadataResponseContestManagersItem[];
}
