/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface CreateCommunityResponseCommunity {
    id: string;
    name: string;
    tier: number;
    spam_tier_level: number;
    chain_node_id?: number;
    default_symbol?: string;
    network?: string;
    base: CommonApi.CreateCommunityResponseCommunityBase;
    icon_url?: string;
    active: boolean;
    type?: CommonApi.CreateCommunityResponseCommunityType;
    description?: string;
    social_links?: CommonApi.CreateCommunityResponseCommunitySocialLinksItem[];
    ss58_prefix?: number;
    stages_enabled?: boolean;
    custom_stages?: string[];
    custom_domain?: string;
    block_explorer_ids?: string;
    collapsed_on_homepage?: boolean;
    default_summary_view?: boolean;
    default_page?: CommonApi.CreateCommunityResponseCommunityDefaultPage;
    has_homepage?: CommonApi.CreateCommunityResponseCommunityHasHomepage;
    terms?: CommonApi.CreateCommunityResponseCommunityTerms;
    admin_only_polling?: boolean;
    ai_features_enabled: boolean;
    bech32_prefix?: string;
    hide_projects?: boolean;
    token_name?: string;
    ce_verbose?: boolean;
    discord_config_id?: number;
    category?: unknown;
    discord_bot_webhooks_enabled?: boolean;
    directory_page_enabled?: boolean;
    directory_page_chain_node_id?: number;
    namespace?: string;
    namespace_address?: string;
    namespace_creator_address?: string;
    namespace_verification_configured?: boolean;
    namespace_nominations?: string[];
    namespace_verified?: boolean;
    redirect?: string;
    snapshot_spaces?: string[];
    include_in_digest_email?: boolean;
    profile_count?: number;
    lifetime_thread_count?: number;
    banner_text?: string;
    allow_tokenized_threads?: boolean;
    thread_purchase_token?: string;
    environment?: string;
    pending_namespace_judge_token_id?: number;
    created_at?: string;
    updated_at?: string;
    Addresses?: CommonApi.CreateCommunityResponseCommunityAddressesItem[];
    CommunityStakes?: CommonApi.CreateCommunityResponseCommunityCommunityStakesItem[];
    CommunityTags?: CommonApi.CreateCommunityResponseCommunityCommunityTagsItem[];
    ChainNode?: CommonApi.CreateCommunityResponseCommunityChainNode;
    topics?: CommonApi.CreateCommunityResponseCommunityTopicsItem[];
    groups?: CommonApi.CreateCommunityResponseCommunityGroupsItem[];
    contest_managers?: CommonApi.CreateCommunityResponseCommunityContestManagersItem[];
}
