/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateCommunityResponseCommunityGroupsItemRequirementsItemThresholdDataSourceObjectId {
    source_type: "sui_native";
    sui_network: string;
    object_id?: string;
}
