/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The environment that created the contest manager
 */
export type CreateGroupResponseContestManagersItemEnvironment =
    | "local"
    | "CI"
    | "frick"
    | "frack"
    | "beta"
    | "demo"
    | "production";
export const CreateGroupResponseContestManagersItemEnvironment = {
    Local: "local",
    Ci: "CI",
    Frick: "frick",
    Frack: "frack",
    Beta: "beta",
    Demo: "demo",
    Production: "production",
} as const;
