/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CreateContestMetadataResponseContestManagersItemTopicsItemWeightedVoting = "stake" | "erc20";
export const CreateContestMetadataResponseContestManagersItemTopicsItemWeightedVoting = {
    Stake: "stake",
    Erc20: "erc20",
} as const;
