/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateGroupRequestMetadata {
    name: string;
    description: string;
    groupImageUrl?: string;
    required_requirements?: number;
    membership_ttl?: number;
}
