/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CreateGroupResponseDefaultPage = "default_all_discussions_view" | "default_summary_view" | "homepage";

export const CreateGroupResponseDefaultPage = {
    DefaultAllDiscussionsView: "default_all_discussions_view",
    DefaultSummaryView: "default_summary_view",
    Homepage: "homepage",
} as const;
