/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CreateGroupRequestRequirementsItemThresholdDataSourceThreeSourceType = "cw721" | "cw20";
export const CreateGroupRequestRequirementsItemThresholdDataSourceThreeSourceType = {
    Cw721: "cw721",
    Cw20: "cw20",
} as const;
