/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface CreateGroupResponseGroupsItemGroupGatedActionsItem {
    group_id: number;
    topic_id: number;
    is_private: boolean;
    gated_actions: CommonApi.CreateGroupResponseGroupsItemGroupGatedActionsItemGatedActionsItem[];
    created_at?: string;
    updated_at?: string;
}
