/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Type of content action
 */
export type CreateContestMetadataResponseContestManagersItemContestsItemActionsItemAction = "added" | "upvoted";
export const CreateContestMetadataResponseContestManagersItemContestsItemActionsItemAction = {
    Added: "added",
    Upvoted: "upvoted",
} as const;
