/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export type CreateGroupResponseGroupsItemRequirementsItemThresholdDataSource =
    | CommonApi.CreateGroupResponseGroupsItemRequirementsItemThresholdDataSourceTokenId
    | CommonApi.CreateGroupResponseGroupsItemRequirementsItemThresholdDataSourceOne
    | CommonApi.CreateGroupResponseGroupsItemRequirementsItemThresholdDataSourceTokenSymbol
    | CommonApi.CreateGroupResponseGroupsItemRequirementsItemThresholdDataSourceThree
    | CommonApi.CreateGroupResponseGroupsItemRequirementsItemThresholdDataSourceContractAddress
    | CommonApi.CreateGroupResponseGroupsItemRequirementsItemThresholdDataSourceObjectId
    | CommonApi.CreateGroupResponseGroupsItemRequirementsItemThresholdDataSourceCoinType;
