/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateCommunityResponseCommunityChainNodeAlchemyMetadata {
    network_id: string;
    price_api_supported: boolean;
    transfer_api_supported: boolean;
}
