/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateCommunityResponseCommunityGroupsItemRequirementsItemThresholdDataSourceCoinType {
    source_type: "sui_token";
    sui_network: string;
    coin_type: string;
}
