/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface DeleteContestMetadataResponse {
    contest_managers: CommonApi.DeleteContestMetadataResponseContestManagersItem[];
}
