/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetCommunitiesResponseResultsItemCommunityStakesItemStakeTransactionsItemStakeDirection = "buy" | "sell";

export const GetCommunitiesResponseResultsItemCommunityStakesItemStakeTransactionsItemStakeDirection = {
    Buy: "buy",
    Sell: "sell",
} as const;
