/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetCommunitiesRequestNetwork =
    | "ethereum"
    | "erc20"
    | "erc721"
    | "erc1155"
    | "edgeware"
    | "osmosis"
    | "injective"
    | "solana"
    | "terra"
    | "near"
    | "stargaze"
    | "evmos"
    | "kava"
    | "kyve";
export const GetCommunitiesRequestNetwork = {
    Ethereum: "ethereum",
    Erc20: "erc20",
    Erc721: "erc721",
    Erc1155: "erc1155",
    Edgeware: "edgeware",
    Osmosis: "osmosis",
    Injective: "injective",
    Solana: "solana",
    Terra: "terra",
    Near: "near",
    Stargaze: "stargaze",
    Evmos: "evmos",
    Kava: "kava",
    Kyve: "kyve",
} as const;
