/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetCommunityResponseAddressesAddressesItemUserEmailNotificationInterval = "weekly" | "never";

export const GetCommunityResponseAddressesAddressesItemUserEmailNotificationInterval = {
    Weekly: "weekly",
    Never: "never",
} as const;
