/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetCommunitiesResponseResultsItemType = "chain" | "dao" | "token" | "offchain";
export const GetCommunitiesResponseResultsItemType = {
    Chain: "chain",
    Dao: "dao",
    Token: "token",
    Offchain: "offchain",
} as const;
