/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export type GetCommunitiesResponseResultsItemGroupsItemRequirementsItemThresholdDataSource =
    | CommonApi.GetCommunitiesResponseResultsItemGroupsItemRequirementsItemThresholdDataSourceTokenId
    | CommonApi.GetCommunitiesResponseResultsItemGroupsItemRequirementsItemThresholdDataSourceOne
    | CommonApi.GetCommunitiesResponseResultsItemGroupsItemRequirementsItemThresholdDataSourceTokenSymbol
    | CommonApi.GetCommunitiesResponseResultsItemGroupsItemRequirementsItemThresholdDataSourceThree;
