/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetCommunitiesResponseResultsItemDefaultPage =
    | "default_all_discussions_view"
    | "default_summary_view"
    | "homepage";
export const GetCommunitiesResponseResultsItemDefaultPage = {
    DefaultAllDiscussionsView: "default_all_discussions_view",
    DefaultSummaryView: "default_summary_view",
    Homepage: "homepage",
} as const;
