/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetCommunitiesResponseResultsItemGroupsItemRequirementsItemThresholdDataSourceContractAddress {
    source_type: CommonApi.GetCommunitiesResponseResultsItemGroupsItemRequirementsItemThresholdDataSourceContractAddressSourceType;
    solana_network: string;
    contract_address: string;
}
