/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetCommunitiesResponseResultsItemAddressesItemUserEmailNotificationInterval = "weekly" | "never";

export const GetCommunitiesResponseResultsItemAddressesItemUserEmailNotificationInterval = {
    Weekly: "weekly",
    Never: "never",
} as const;
