/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetCommunityResponseAddressesGroupsItemRequirementsItemThresholdDataSourceTokenSymbol {
    source_type: "cosmos_native";
    cosmos_chain_id: string;
    token_symbol: string;
}
