/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetCommunitiesRequestRelevanceBy = "tag_ids" | "membership";
export const GetCommunitiesRequestRelevanceBy = {
    TagIds: "tag_ids",
    Membership: "membership",
} as const;
