/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetMembersResponseResultsItemAddressesItem {
    id: number;
    community_id: string;
    address: string;
    stake_balance?: number;
    role: string;
}
