/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetMembersResponseResultsItemAddressesItem {
    id: number;
    communityId: string;
    address: string;
    stakeBalance?: number;
    role: CommonApi.GetMembersResponseResultsItemAddressesItemRole;
}
