/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type JoinCommunityResponseBase = "cosmos" | "substrate" | "ethereum" | "near" | "solana";

export const JoinCommunityResponseBase = {
    Cosmos: "cosmos",
    Substrate: "substrate",
    Ethereum: "ethereum",
    Near: "near",
    Solana: "solana",
} as const;
