/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateCommunityResponseContestManagersItemContestsItemScoreItem {
    creator_address: string;
    content_id: string;
    votes: string;
    prize: string;
    tickerPrize?: number;
}
