/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export type UpdateGroupResponseRequirementsItemThresholdDataSource =
    | CommonApi.UpdateGroupResponseRequirementsItemThresholdDataSourceTokenId
    | CommonApi.UpdateGroupResponseRequirementsItemThresholdDataSourceOne
    | CommonApi.UpdateGroupResponseRequirementsItemThresholdDataSourceTokenSymbol
    | CommonApi.UpdateGroupResponseRequirementsItemThresholdDataSourceThree;
