/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UpdateCommunityRequestChainNodeCosmosGovVersion =
    | "v1"
    | "v1atomone"
    | "v1beta1govgen"
    | "v1beta1"
    | "v1beta1-attempt-failed"
    | "v1-attempt-failed";
export const UpdateCommunityRequestChainNodeCosmosGovVersion = {
    V1: "v1",
    V1Atomone: "v1atomone",
    V1Beta1Govgen: "v1beta1govgen",
    V1Beta1: "v1beta1",
    V1Beta1AttemptFailed: "v1beta1-attempt-failed",
    V1AttemptFailed: "v1-attempt-failed",
} as const;
