/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UpdateCommunityResponseChainNodeHealth = "failed" | "healthy";
export const UpdateCommunityResponseChainNodeHealth = {
    Failed: "failed",
    Healthy: "healthy",
} as const;
