/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UpdateGroupResponseRequirementsItemThresholdDataSourceThreeSourceType = "cw721" | "cw20";

export const UpdateGroupResponseRequirementsItemThresholdDataSourceThreeSourceType = {
    Cw721: "cw721",
    Cw20: "cw20",
} as const;
