/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UpdateCommunityResponseGroupsItemRequirementsItemThresholdDataSourceContractAddressSourceType =
    | "spl"
    | "metaplex";
export const UpdateCommunityResponseGroupsItemRequirementsItemThresholdDataSourceContractAddressSourceType = {
    Spl: "spl",
    Metaplex: "metaplex",
} as const;
