/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UpdateGroupResponseRequirementsItemThresholdDataSourceContractAddressSourceType = "spl" | "metaplex";
export const UpdateGroupResponseRequirementsItemThresholdDataSourceContractAddressSourceType = {
    Spl: "spl",
    Metaplex: "metaplex",
} as const;
