/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UpdateCommunityResponseChainNodeBalanceType =
    | "terra"
    | "ethereum"
    | "solana"
    | "cosmos"
    | "near"
    | "substrate"
    | "sui";
export const UpdateCommunityResponseChainNodeBalanceType = {
    Terra: "terra",
    Ethereum: "ethereum",
    Solana: "solana",
    Cosmos: "cosmos",
    Near: "near",
    Substrate: "substrate",
    Sui: "sui",
} as const;
