/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UpdateCommunityResponseHasHomepage = "true" | "false";
export const UpdateCommunityResponseHasHomepage = {
    True: "true",
    False: "false",
} as const;
