/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UpdateCommunityRequestAddressesItemUserEmailNotificationInterval = "weekly" | "never";
export const UpdateCommunityRequestAddressesItemUserEmailNotificationInterval = {
    Weekly: "weekly",
    Never: "never",
} as const;
