/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UpdateCommunityResponseContestManagersItemTopicsItemWeightedVoting = "stake" | "erc20";

export const UpdateCommunityResponseContestManagersItemTopicsItemWeightedVoting = {
    Stake: "stake",
    Erc20: "erc20",
} as const;
