/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as CommonApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const CreateCommentReactionRequest: core.serialization.Schema<
    serializers.CreateCommentReactionRequest.Raw,
    CommonApi.CreateCommentReactionRequest
> = core.serialization.object({
    commentId: core.serialization.property("comment_id", core.serialization.number()),
    commentMsgId: core.serialization.property("comment_msg_id", core.serialization.string().optional()),
    canvasSignedData: core.serialization.property("canvas_signed_data", core.serialization.string().optional()),
    canvasMsgId: core.serialization.property("canvas_msg_id", core.serialization.string().optional()),
});

export declare namespace CreateCommentReactionRequest {
    interface Raw {
        comment_id: number;
        comment_msg_id?: string | null;
        canvas_signed_data?: string | null;
        canvas_msg_id?: string | null;
    }
}
