/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AddLinksResponseCollaboratorsItemUserProfileTagsItemTag {
    id?: number;
    name: string;
    created_at?: string;
    updated_at?: string;
}
