/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AddLinksResponseAddressUserEmailNotificationInterval = "weekly" | "never";
export const AddLinksResponseAddressUserEmailNotificationInterval = {
    Weekly: "weekly",
    Never: "never",
} as const;
