/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AddLinksResponseReactionsItemAddressUserEmailNotificationInterval = "weekly" | "never";
export const AddLinksResponseReactionsItemAddressUserEmailNotificationInterval = {
    Weekly: "weekly",
    Never: "never",
} as const;
