/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CreateThreadResponseCollaboratorsItemUserEmailNotificationInterval = "weekly" | "never";
export const CreateThreadResponseCollaboratorsItemUserEmailNotificationInterval = {
    Weekly: "weekly",
    Never: "never",
} as const;
