/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface CreateThreadResponseCollaboratorsItemUserProfileTagsItem {
    userId: number;
    tagId: number;
    createdAt?: Date;
    updatedAt?: Date;
    tag?: CommonApi.CreateThreadResponseCollaboratorsItemUserProfileTagsItemTag;
}
