/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface CreateThreadRequestDiscordMeta {
    user: CommonApi.CreateThreadRequestDiscordMetaUser;
    channel_id: string;
    message_id: string;
}
