/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CreateThreadResponseLinksItemSource = "snapshot" | "proposal" | "thread" | "web" | "template";
export const CreateThreadResponseLinksItemSource = {
    Snapshot: "snapshot",
    Proposal: "proposal",
    Thread: "thread",
    Web: "web",
    Template: "template",
} as const;
