/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface CreateThreadResponseReactionAddress {
    id?: number;
    address: string;
    communityId: string;
    userId?: number;
    verificationToken?: string;
    verificationTokenExpires?: Date;
    verified?: Date;
    lastActive?: Date;
    ghostAddress?: boolean;
    walletId?: CommonApi.CreateThreadResponseReactionAddressWalletId;
    blockInfo?: string;
    isUserDefault?: boolean;
    role?: CommonApi.CreateThreadResponseReactionAddressRole;
    isBanned?: boolean;
    hex?: string;
    user?: CommonApi.CreateThreadResponseReactionAddressUser;
    createdAt?: Date;
    updatedAt?: Date;
}
