/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type DeleteLinksResponseReactionAddressUserEmailNotificationInterval = "weekly" | "never";
export const DeleteLinksResponseReactionAddressUserEmailNotificationInterval = {
    Weekly: "weekly",
    Never: "never",
} as const;
