/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type DeleteLinksResponseReactionsItemAddressUserEmailNotificationInterval = "weekly" | "never";
export const DeleteLinksResponseReactionsItemAddressUserEmailNotificationInterval = {
    Weekly: "weekly",
    Never: "never",
} as const;
