/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DeleteThreadResponse {
    thread_id: number;
    community_id: string;
    canvas_signed_data?: string;
    canvas_msg_id?: string;
}
