/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type DeleteLinksResponseAddressRole = "admin" | "moderator" | "member";
export const DeleteLinksResponseAddressRole = {
    Admin: "admin",
    Moderator: "moderator",
    Member: "member",
} as const;
