/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetLinksResponse {
    links?: CommonApi.GetLinksResponseLinksItem[];
    threads?: CommonApi.GetLinksResponseThreadsItem[];
}
