/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetThreadsResponseResultsItemReactionAddressUserEmailNotificationInterval = "weekly" | "never";
export const GetThreadsResponseResultsItemReactionAddressUserEmailNotificationInterval = {
    Weekly: "weekly",
    Never: "never",
} as const;
