/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetThreadsRequestOrderBy = "newest" | "oldest" | "mostLikes" | "mostComments" | "latestActivity";
export const GetThreadsRequestOrderBy = {
    Newest: "newest",
    Oldest: "oldest",
    MostLikes: "mostLikes",
    MostComments: "mostComments",
    LatestActivity: "latestActivity",
} as const;
