/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetThreadsResponseThreadsItemTopicWeightedVoting = "stake" | "erc20";

export const GetThreadsResponseThreadsItemTopicWeightedVoting = {
    Stake: "stake",
    Erc20: "erc20",
} as const;
