/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetThreadsResponseThreadsItemCollaboratorsItemUserProfileTagsItem {
    user_id: number;
    tag_id: number;
    created_at?: CommonApi.GetThreadsResponseThreadsItemCollaboratorsItemUserProfileTagsItemCreatedAt;
    updated_at?: CommonApi.GetThreadsResponseThreadsItemCollaboratorsItemUserProfileTagsItemUpdatedAt;
    Tag?: CommonApi.GetThreadsResponseThreadsItemCollaboratorsItemUserProfileTagsItemTag;
}
