/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetThreadsResponseThreadsItemCommentsItemAddress {
    id: number;
    address: string;
    communityId: string;
    userId?: number;
    verificationToken?: string;
    verificationTokenExpires?: CommonApi.GetThreadsResponseThreadsItemCommentsItemAddressVerificationTokenExpires;
    verified?: CommonApi.GetThreadsResponseThreadsItemCommentsItemAddressVerified;
    lastActive?: CommonApi.GetThreadsResponseThreadsItemCommentsItemAddressLastActive;
    ghostAddress?: boolean;
    walletId?: CommonApi.GetThreadsResponseThreadsItemCommentsItemAddressWalletId;
    blockInfo?: string;
    isUserDefault?: boolean;
    role?: CommonApi.GetThreadsResponseThreadsItemCommentsItemAddressRole;
    isBanned?: boolean;
    hex?: string;
    user?: CommonApi.GetThreadsResponseThreadsItemCommentsItemAddressUser;
    createdAt?: CommonApi.GetThreadsResponseThreadsItemCommentsItemAddressCreatedAt;
    updatedAt?: CommonApi.GetThreadsResponseThreadsItemCommentsItemAddressUpdatedAt;
}
