/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetThreadsResponseResultsItemCommentsItemAddress {
    id: number;
    address: string;
    community_id: string;
    user_id?: number;
    verification_token?: string;
    verification_token_expires?: CommonApi.GetThreadsResponseResultsItemCommentsItemAddressVerificationTokenExpires;
    verified?: CommonApi.GetThreadsResponseResultsItemCommentsItemAddressVerified;
    last_active?: CommonApi.GetThreadsResponseResultsItemCommentsItemAddressLastActive;
    ghost_address?: boolean;
    wallet_id?: CommonApi.GetThreadsResponseResultsItemCommentsItemAddressWalletId;
    block_info?: string;
    role?: CommonApi.GetThreadsResponseResultsItemCommentsItemAddressRole;
    is_banned?: boolean;
    hex?: string;
    User?: CommonApi.GetThreadsResponseResultsItemCommentsItemAddressUser;
    created_at?: CommonApi.GetThreadsResponseResultsItemCommentsItemAddressCreatedAt;
    updated_at?: CommonApi.GetThreadsResponseResultsItemCommentsItemAddressUpdatedAt;
}
