/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetThreadsResponseThreadsItemAssociatedContestsItem {
    /** On-Chain Contest Manager */
    ContestManager: CommonApi.GetThreadsResponseThreadsItemAssociatedContestsItemContestManager;
    contest_id: number;
    contest_address: string;
    start_time: CommonApi.GetThreadsResponseThreadsItemAssociatedContestsItemStartTime;
    end_time: CommonApi.GetThreadsResponseThreadsItemAssociatedContestsItemEndTime;
    score: CommonApi.GetThreadsResponseThreadsItemAssociatedContestsItemScoreItem[];
    contest_name?: string;
    contest_interval?: number;
    content_id?: number;
    contest_cancelled?: boolean;
    thread_id?: number;
}
