/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetThreadsResponseThreadsItemReactionsItem {
    id: number;
    addressId: number;
    reaction: "like";
    threadId?: number;
    commentId?: number;
    proposalId?: number;
    calculatedVotingWeight?: string;
    canvasSignedData?: unknown;
    canvasMsgId?: string;
    createdAt?: CommonApi.GetThreadsResponseThreadsItemReactionsItemCreatedAt;
    updatedAt?: CommonApi.GetThreadsResponseThreadsItemReactionsItemUpdatedAt;
    address?: CommonApi.GetThreadsResponseThreadsItemReactionsItemAddress;
    address?: string;
    lastActive?: CommonApi.GetThreadsResponseThreadsItemReactionsItemLastActive;
    profileName?: string;
    avatarUrl?: string;
}
