/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetThreadsResponseThreadsItemContestActionsItemContestScoreItem {
    prize: string;
    votes: string;
    contentId: string;
    creatorAddress: string;
}
