/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetThreadsResponseResultsItemCommentsItemAddressUserEmailNotificationInterval = "weekly" | "never";
export const GetThreadsResponseResultsItemCommentsItemAddressUserEmailNotificationInterval = {
    Weekly: "weekly",
    Never: "never",
} as const;
