/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetThreadsResponseResultsItemReactionsItemAddressUserProfileTagsItem {
    user_id: number;
    tag_id: number;
    created_at?: CommonApi.GetThreadsResponseResultsItemReactionsItemAddressUserProfileTagsItemCreatedAt;
    updated_at?: CommonApi.GetThreadsResponseResultsItemReactionsItemAddressUserProfileTagsItemUpdatedAt;
}
