/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetThreadsResponseThreadsItemTopic {
    id?: number;
    name?: string;
    communityId: string;
    description?: string;
    telegram?: string;
    featuredInSidebar?: boolean;
    featuredInNewPost?: boolean;
    defaultOffchainTemplate?: string;
    order?: number;
    channelId?: string;
    groupIds?: number[];
    defaultOffchainTemplateBackup?: string;
    weightedVoting?: CommonApi.GetThreadsResponseThreadsItemTopicWeightedVoting;
    /** token address, used for ERC20 topics */
    tokenAddress?: string;
    /** token symbol, used for ERC20 topics */
    tokenSymbol?: string;
    /** vote weight multiplier, used for ERC20 topics */
    voteWeightMultiplier?: number;
    createdAt?: string;
    updatedAt?: string;
    deletedAt?: string;
    archivedAt?: string;
    contestTopics?: unknown;
    totalThreads?: number;
    activeContestManagers?: CommonApi.GetThreadsResponseThreadsItemTopicActiveContestManagersItem[];
}
