/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetThreadsResponseThreadsItemDiscordMeta {
    user: CommonApi.GetThreadsResponseThreadsItemDiscordMetaUser;
    channelId: string;
    messageId: string;
}
