/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetThreadsResponseThreadsItemCommentsItemReactionAddressUserProfileTagsItem {
    user_id: number;
    tag_id: number;
    created_at?: CommonApi.GetThreadsResponseThreadsItemCommentsItemReactionAddressUserProfileTagsItemCreatedAt;
    updated_at?: CommonApi.GetThreadsResponseThreadsItemCommentsItemReactionAddressUserProfileTagsItemUpdatedAt;
    Tag?: CommonApi.GetThreadsResponseThreadsItemCommentsItemReactionAddressUserProfileTagsItemTag;
}
