/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetThreadsResponse {
    page: number;
    limit: number;
    numVotingThreads: number;
    threads: CommonApi.GetThreadsResponseThreadsItem[];
}
