/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetThreadsResponseThreadsItemCommentsItemAddressUserEmailNotificationInterval = "weekly" | "never";

export const GetThreadsResponseThreadsItemCommentsItemAddressUserEmailNotificationInterval = {
    Weekly: "weekly",
    Never: "never",
} as const;
