/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetThreadsResponseThreadsItemCollaboratorsItem {
    id: number;
    address: string;
    communityId: string;
    userId?: number;
    verificationToken?: string;
    verificationTokenExpires?: CommonApi.GetThreadsResponseThreadsItemCollaboratorsItemVerificationTokenExpires;
    verified?: CommonApi.GetThreadsResponseThreadsItemCollaboratorsItemVerified;
    lastActive?: CommonApi.GetThreadsResponseThreadsItemCollaboratorsItemLastActive;
    ghostAddress?: boolean;
    walletId?: CommonApi.GetThreadsResponseThreadsItemCollaboratorsItemWalletId;
    blockInfo?: string;
    isUserDefault?: boolean;
    role?: CommonApi.GetThreadsResponseThreadsItemCollaboratorsItemRole;
    isBanned?: boolean;
    hex?: string;
    user?: CommonApi.GetThreadsResponseThreadsItemCollaboratorsItemUser;
    createdAt?: CommonApi.GetThreadsResponseThreadsItemCollaboratorsItemCreatedAt;
    updatedAt?: CommonApi.GetThreadsResponseThreadsItemCollaboratorsItemUpdatedAt;
}
