/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetThreadsResponseResultsItemCollaboratorsItemUserProfileTagsItem {
    user_id: number;
    tag_id: number;
    created_at?: CommonApi.GetThreadsResponseResultsItemCollaboratorsItemUserProfileTagsItemCreatedAt;
    updated_at?: CommonApi.GetThreadsResponseResultsItemCollaboratorsItemUserProfileTagsItemUpdatedAt;
}
