/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetThreadsResponseThreadsItemContestActionsItemContest {
    /** On-Chain Contest Manager */
    ContestManager: CommonApi.GetThreadsResponseThreadsItemContestActionsItemContestContestManager;
    contest_id: number;
    contest_address: string;
    start_time: CommonApi.GetThreadsResponseThreadsItemContestActionsItemContestStartTime;
    end_time: CommonApi.GetThreadsResponseThreadsItemContestActionsItemContestEndTime;
    score: CommonApi.GetThreadsResponseThreadsItemContestActionsItemContestScoreItem[];
    contest_name?: string;
    contest_interval?: number;
    content_id?: number;
    contest_cancelled?: boolean;
    thread_id?: number;
}
