/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetThreadsResponseResultsItemCollaboratorsItem {
    id: number;
    address: string;
    community_id: string;
    user_id?: number;
    verification_token?: string;
    verification_token_expires?: CommonApi.GetThreadsResponseResultsItemCollaboratorsItemVerificationTokenExpires;
    verified?: CommonApi.GetThreadsResponseResultsItemCollaboratorsItemVerified;
    last_active?: CommonApi.GetThreadsResponseResultsItemCollaboratorsItemLastActive;
    ghost_address?: boolean;
    wallet_id?: CommonApi.GetThreadsResponseResultsItemCollaboratorsItemWalletId;
    block_info?: string;
    role?: CommonApi.GetThreadsResponseResultsItemCollaboratorsItemRole;
    is_banned?: boolean;
    hex?: string;
    User?: CommonApi.GetThreadsResponseResultsItemCollaboratorsItemUser;
    created_at?: CommonApi.GetThreadsResponseResultsItemCollaboratorsItemCreatedAt;
    updated_at?: CommonApi.GetThreadsResponseResultsItemCollaboratorsItemUpdatedAt;
}
