/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetThreadsResponseThreadsItemReactionsItemAddress {
    id: number;
    address: string;
    community_id: string;
    user_id?: number;
    verification_token?: string;
    verification_token_expires?: CommonApi.GetThreadsResponseThreadsItemReactionsItemAddressVerificationTokenExpires;
    verified?: CommonApi.GetThreadsResponseThreadsItemReactionsItemAddressVerified;
    last_active?: CommonApi.GetThreadsResponseThreadsItemReactionsItemAddressLastActive;
    ghost_address?: boolean;
    wallet_id?: CommonApi.GetThreadsResponseThreadsItemReactionsItemAddressWalletId;
    block_info?: string;
    is_user_default?: boolean;
    role?: CommonApi.GetThreadsResponseThreadsItemReactionsItemAddressRole;
    is_banned?: boolean;
    hex?: string;
    User?: CommonApi.GetThreadsResponseThreadsItemReactionsItemAddressUser;
    created_at?: CommonApi.GetThreadsResponseThreadsItemReactionsItemAddressCreatedAt;
    updated_at?: CommonApi.GetThreadsResponseThreadsItemReactionsItemAddressUpdatedAt;
}
