/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetThreadsResponseThreadsItemReactionsItemAddressUser {
    id: number;
    email?: string;
    isAdmin?: boolean;
    disableRichText?: boolean;
    emailVerified?: boolean;
    selectedCommunityId?: string;
    emailNotificationInterval?: CommonApi.GetThreadsResponseThreadsItemReactionsItemAddressUserEmailNotificationInterval;
    promotionalEmailsEnabled?: boolean;
    isWelcomeOnboardFlowComplete?: boolean;
    profile: CommonApi.GetThreadsResponseThreadsItemReactionsItemAddressUserProfile;
    xpPoints?: number;
    profileTags?: CommonApi.GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItem[];
    apiKey?: unknown;
    createdAt?: CommonApi.GetThreadsResponseThreadsItemReactionsItemAddressUserCreatedAt;
    updatedAt?: CommonApi.GetThreadsResponseThreadsItemReactionsItemAddressUserUpdatedAt;
}
