/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItem {
    userId: number;
    tagId: number;
    createdAt?: CommonApi.GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItemCreatedAt;
    updatedAt?: CommonApi.GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItemUpdatedAt;
    tag?: CommonApi.GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItemTag;
}
