/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetThreadsResponseThreadsItemReactionAddress {
    id: number;
    address: string;
    community_id: string;
    user_id?: number;
    verification_token?: string;
    verification_token_expires?: CommonApi.GetThreadsResponseThreadsItemReactionAddressVerificationTokenExpires;
    verified?: CommonApi.GetThreadsResponseThreadsItemReactionAddressVerified;
    last_active?: CommonApi.GetThreadsResponseThreadsItemReactionAddressLastActive;
    ghost_address?: boolean;
    wallet_id?: CommonApi.GetThreadsResponseThreadsItemReactionAddressWalletId;
    block_info?: string;
    is_user_default?: boolean;
    role?: CommonApi.GetThreadsResponseThreadsItemReactionAddressRole;
    is_banned?: boolean;
    hex?: string;
    User?: CommonApi.GetThreadsResponseThreadsItemReactionAddressUser;
    created_at?: CommonApi.GetThreadsResponseThreadsItemReactionAddressCreatedAt;
    updated_at?: CommonApi.GetThreadsResponseThreadsItemReactionAddressUpdatedAt;
}
