/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetThreadsResponseResultsItemReactionAddress {
    id: number;
    address: string;
    community_id: string;
    user_id?: number;
    verification_token?: string;
    verification_token_expires?: CommonApi.GetThreadsResponseResultsItemReactionAddressVerificationTokenExpires;
    verified?: CommonApi.GetThreadsResponseResultsItemReactionAddressVerified;
    last_active?: CommonApi.GetThreadsResponseResultsItemReactionAddressLastActive;
    ghost_address?: boolean;
    wallet_id?: CommonApi.GetThreadsResponseResultsItemReactionAddressWalletId;
    block_info?: string;
    role?: CommonApi.GetThreadsResponseResultsItemReactionAddressRole;
    is_banned?: boolean;
    hex?: string;
    User?: CommonApi.GetThreadsResponseResultsItemReactionAddressUser;
    created_at?: CommonApi.GetThreadsResponseResultsItemReactionAddressCreatedAt;
    updated_at?: CommonApi.GetThreadsResponseResultsItemReactionAddressUpdatedAt;
}
