/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetThreadsResponseThreadsItemAddressUserProfileTagsItem {
    user_id: number;
    tag_id: number;
    created_at?: CommonApi.GetThreadsResponseThreadsItemAddressUserProfileTagsItemCreatedAt;
    updated_at?: CommonApi.GetThreadsResponseThreadsItemAddressUserProfileTagsItemUpdatedAt;
    Tag?: CommonApi.GetThreadsResponseThreadsItemAddressUserProfileTagsItemTag;
}
