/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetThreadsResponseThreadsItemReactionAddressUserProfileBackgroundImage {
    url?: string;
    imageBehavior?: string;
}
