/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CommonApi from "../../../index";

export interface GetThreadsResponseThreadsItemAddressUser {
    id: number;
    email?: string;
    isAdmin?: boolean;
    disableRichText?: boolean;
    emailVerified?: boolean;
    selected_community_id?: string;
    emailNotificationInterval?: CommonApi.GetThreadsResponseThreadsItemAddressUserEmailNotificationInterval;
    promotional_emails_enabled?: boolean;
    is_welcome_onboard_flow_complete?: boolean;
    profile: CommonApi.GetThreadsResponseThreadsItemAddressUserProfile;
    xp_points?: number;
    created_at?: CommonApi.GetThreadsResponseThreadsItemAddressUserCreatedAt;
    updated_at?: CommonApi.GetThreadsResponseThreadsItemAddressUserUpdatedAt;
    ProfileTags?: CommonApi.GetThreadsResponseThreadsItemAddressUserProfileTagsItem[];
    unsubscribe_uuid?: string;
}
