/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetThreadsResponseThreadsItemReactionsItemAddressUserProfileTagsItemTag {
    id?: number;
    name: string;
}
