/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UpdateThreadResponseReactionAddressUserEmailNotificationInterval = "weekly" | "never";
export const UpdateThreadResponseReactionAddressUserEmailNotificationInterval = {
    Weekly: "weekly",
    Never: "never",
} as const;
