/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UpdateThreadResponseTopicWeightedVoting = "stake" | "erc20";
export const UpdateThreadResponseTopicWeightedVoting = {
    Stake: "stake",
    Erc20: "erc20",
} as const;
