/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateThreadResponseThreadVersionHistoriesItem {
    id?: number;
    thread_id: number;
    /** Address of the creator of the post or the collaborator */
    address: string;
    body: string;
    timestamp: string;
    content_url?: string;
}
