/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UpdateThreadResponseReactionsItemAddressUserEmailNotificationInterval = "weekly" | "never";
export const UpdateThreadResponseReactionsItemAddressUserEmailNotificationInterval = {
    Weekly: "weekly",
    Never: "never",
} as const;
