/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UpdateThreadResponseAddressUserEmailNotificationInterval = "weekly" | "never";
export const UpdateThreadResponseAddressUserEmailNotificationInterval = {
    Weekly: "weekly",
    Never: "never",
} as const;
