/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         communityId: "community_id"
 *     }
 */
export interface GetAllContestsRequest {
    communityId: string;
    contestAddress?: string;
    contestId?: number;
    running?: boolean;
}
